### ISSUE TITLE
Drop .NET 6 target

### ISSUE THREAD

**Issue by paulirwin** [apache/lucenenet#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Task description

We should drop the .NET 6 target now that it is no longer supported with security updates. Any users still on .NET 6 can use the netstandard2.1 target.

This will leave the following targets:
- net462
- netstandard2.0
- netstandard2.1
- net8.0

**Comment by NightOwl888** [comment]
Note that once we drop the `net6.0` target, we can use `net6.0` for testing `netstandard2.1` instead of `net5.0`.
