### ISSUE TITLE
Factor out ICheckSum and replace with System.Security.Cryptography.HashAlgorithm

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#255]
<p><tt>IChecksum</tt> was brought over from Java in order to plug in the <tt>CRC32</tt> class.</p>

<p>However, .NET already has its own abstract class, <a href="https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm" class="external-link" rel="nofollow">HashAlgorithm</a> that is used to as a base class for all cryptographic algorithms. There are also several 3rd party implementations of CRC32 that implement <tt>HashAlgorithm</tt> that we could use (provided we drop support for .NET framework < 4.6.1). <a href="https://www.nuget.org/packages/Crc32.NET/" class="external-link" rel="nofollow">Crc32.NET</a> claims to be one of the fastest implementations.</p>

<p><tt>IChecksum</tt> is only utilized in a couple of places, but Lucene.NET's types should also be renamed accordingly to show they are using <tt>HashAlgorigthm</tt> instead of <tt>IChecksum</tt>:</p>

<ul>
	<li><tt>BufferedChecksum</tt> > <tt>BufferedHashAlgorithm</tt></li>
	<li><tt>BufferedChecksumIndexInput</tt> > <tt>BufferedHashAlgorithmIndexInput</tt></li>
</ul>

<p>The APIs between <tt>IChecksum</tt> and <tt>HashAlgorithm</tt> differ, but being that they serve the exact same purpose we should be able to make this work with a bit of refactoring.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-637">[LUCENENET-637]</a> created by nightowl888</i>

**Comment by NightOwl888** [comment]
For now, `IChecksum` and its only implementation, `BufferedChecksum` have been marked internal. We will fix this before the release of Lucene.NET 4.8.0 if there is time, but it is only guaranteed to make it into the release if someone contributes it.

See [https://github.com/apache/lucenenet/issues/248#issuecomment-624406460](https://github.com/apache/lucenenet/issues/248#issuecomment-624406460) for details of what is required.

**Comment by NightOwl888** [comment]
See #436. We are closing this due to the lack of benefit for the change.
