### ISSUE TITLE
Identify/Fix Bottlenecks

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#261]
<p>We need some help profiling Lucene.NET to identify and/or fix any potential bottlenecks. Please make us aware of anything you find by opening a new GitHub issue or by letting us know on the <a href="https://cwiki.apache.org/confluence/display/LUCENENET/Mailing+Lists" class="external-link" rel="nofollow">dev mailing list</a>.</p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-630">[LUCENENET-630]</a> created by nightowl888</i>

**Comment by theolivenbaum** [comment]
Two changes from what I noticed while benchmarking Lucene: #370 and #372 
Working now on a better replace for Debugging.Assert that does not depend a delegate here: #373

**Comment by NightOwl888** [comment]
I am closing this now, as we are finding and reporting bottlenecks as specific issues, so we no longer need a general task for it.
