### ISSUE TITLE
Error using Lucene.Net.Facet 4.8.0-beta00005  with Xamarin.iOS

### ISSUE THREAD

**Issue by clambertus** [apache/lucenenet#273]
<p>I'm using Lucene.Net.Facet 4.8.0-beta00005 in a big Xamarin project.</p>

<p><ins>With Xamarin.Android and Xamarin.UWP it's all right.</ins></p>

<p><b><ins>But With Xamarin.iOS on device (Ipad)</ins></b>, i'm receiving this error:</p>

<p> <em>Attempting to JIT compile method 'Lucene.Net.Support.LurchTable2<Lucene.Net.Facet.Taxonomy.FacetLabel, Lucene.Net.Facet.Taxonomy.Directory.DirectoryTaxonomyReader/Int32Class>:InternalInsert<Lucene.Net.Support.LurchTable2/Add2Info<Lucene.Net.Facet.Taxonomy.FacetLabel, Lucene.Net.Facet.Taxonomy.Directory.DirectoryTaxonomyReader/Int32Class>> (int,Lucene.Net.Facet.Taxonomy.FacetLabel,int&,Lucene.Net.Support.LurchTable`2/Add2Info<Lucene.Net.Facet.Taxonomy.FacetLabel, Lucene.Net.Facet.Taxonomy.Directory.DirectoryTaxonomyReader/Int32Class>&)' while running in aot-only mode. See <a href="https://developer.xamarin.com/guides/ios/advanced_topics/limitations/" class="external-link" rel="nofollow">https://developer.xamarin.com/guides/ios/advanced_topics/limitations/</a> for more information.</em></p>

<p><em><font color="#d04437">at Lucene.Net.Support.LurchTable2<span class="error">&#91;TKey,TValue&#93;</span>.Insert<span class="error">&#91;T&#93;</span> (TKey key, T& value) <0x2570f48 + 0x000e0> in <063e095c95d945a4ace32ab83d1227eb#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at (wrapper unknown) System.Object.gsharedvt_in() at Lucene.Net.Support.LurchTable2<span class="error">&#91;TKey,TValue&#93;</span>.AddOrUpdate (TKey key, TValue addValue, Lucene.Net.Support.KeyValueUpdate2<span class="error">&#91;TKey,TValue&#93;</span> fnUpdate) <0x232824c + 0x0013b> in <063e095c95d945a4ace32ab83d1227eb#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at Lucene.Net.Facet.Taxonomy.LRUHashMap2<span class="error">&#91;TKey,TValue&#93;</span>.Put (TKey key, TValue value) <0x2c487f8 + 0x0015b> in <79d3a7b905954d0993025c09c5d087ce#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at Lucene.Net.Facet.Taxonomy.Directory.DirectoryTaxonomyReader.GetOrdinal (Lucene.Net.Facet.Taxonomy.FacetLabel cp) <0x2c51970 + 0x0019b> in <79d3a7b905954d0993025c09c5d087ce#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at Lucene.Net.Facet.Taxonomy.Int32TaxonomyFacets.GetTopChildren</font> (System.Int32 topN, System.String dim, System.String[] path) <0x2c481dc + 0x0008f> in <79d3a7b905954d0993025c09c5d087ce#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at Login.MyMB.Lucene.Client.LuceneArticoliSearcher.GetListaArticoloXRicercaAvanzataConRicercaSemplice (System.Collections.Generic.List1<span class="error">&#91;T&#93;</span> listParametri) <0x224add0 + 0x001bb> in <8f49891e0f0546e185aba7424d294ef7#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at Login.MyMB.Lucene.Client.LuceneArticoliSearcher.GetListaArticoloConRicercaSemplice (System.Collections.Generic.List1<span class="error">&#91;T&#93;</span> listParametri) <0x224afbc + 0x0009f> in <8f49891e0f0546e185aba7424d294ef7#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 at MyMB.Forms.RicercaLucene.RicercaArticoloLucene.GetListaArticoliXRicercaSemplice (Login.MyMB.Interface.IAmbiente ambiente, Login.MyMB.Lucene.Client.LuceneArticoliSearcher las, System.Collections.Generic.List`1<span class="error">&#91;T&#93;</span> ListParametri, System.Boolean isAbilitataRicercaBarcode) <0xe47fc0 + 0x000e7> in <f1bb3149abe145459612794f1a096634#2ae0fea9ea4eacaef83bf2e9713bb8ea>:0 ...............................</em></p>

<p>At the link <a href="https://docs.microsoft.com/it-it/xamarin/ios/internals/limitations" class="external-link" rel="nofollow">https://docs.microsoft.com/it-it/xamarin/ios/internals/limitations</a> , I found the problem cause (I suppose...):</p>

<p><em>Value types as Dictionary Keys Using a value type as a Dictionary<TKey, TValue> key is problematic, as the default Dictionary constructor attempts to use EqualityComparer<TKey>.Default. EqualityComparer<TKey>.Default, in turn, attempts to use Reflection to instantiate a new type which implements the IEqualityComparer<TKey> interface. This works for reference types (as the reflection+create a new type step is skipped), but for value types it crashes and burns rather quickly once you attempt to use it on the device. Workaround: Manually implement the IEqualityComparer<TKey> interface in a new type and provide an instance of that type to the Dictionary<TKey, TValue> (IEqualityComparer<TKey>) constructor.</em></p>

<p>So, what can I do? Thank you in advance, Enrico Caltran +393357485560 <span class="nobr"><a href="mailto:enrico.caltran@timegroup.it" class="external-link" rel="nofollow">enrico.caltran@timegroup.it<sup><img class="rendericon" src="https://issues.apache.org/jira/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span></p>
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/LUCENENET-602">[LUCENENET-602]</a> created by enycaltran</i>

**Comment by NightOwl888** [comment]
This has basically been held open because of https://github.com/NightOwl888/J2N/issues/3, but given the fact this one reporter is no longer interested in a fix and MAUI is right around the corner (which hopefully addresses this), there doesn't seem to be much sense in spending time on this.
