### ISSUE TITLE
Verify compatibility with Luke 4.8.0

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#281]
Luke is a command line utility that can be used to analyze a lucene index. We need to be sure the index files created by Lucene. NET 4.8.0 are compatible with the tool.

https://github.com/DmitryKey/luke/releases/tag/4.8.0

**Comment by Matt2843** [comment]
Personally used this version of Luke on a daily basis for a good while with Lucene.NET 4.8.0 beta indexes (the Luke GUI from the jar file) and have not experienced any issues yet - the indexes I inspect with Luke are however very similar.

**Comment by rclabo** [comment]
I too have used Luke with Lucene.NET 4.8.0 beta indexes (the Luke GUI from the jar file) and have not experienced any issues yet.

**Comment by NightOwl888** [comment]
It sounds like our users have done this for us (thank you). Marking closed.
