### ISSUE TITLE
Investigate Slow Tests in Lucene.Net.Util Namespace

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#295]
As part of #261, here is a list of known tests in the `Lucene.Net.Util` namespace that are taking significantly longer in .NET than they did in Java. The percentage is the amount of time that .NET takes compared to Java (for example, if the .NET test is running 10x longer the percentage will be 1000% of the Java test).

These tests need to be investigated to determine what is causing the slowness. Fixing these issues will likely ripple across the entire project reducing the time the tests take to run as well as impacting end users.

## Slow Running Tests

- [x] Lucene.Net.Util.TestDocIdBitSet.TestAgainstBitSet	(11583% - <b>Now 206%</b>)
- [x] Lucene.Net.Util.TestMathUtil.TestAcoshMethod	(7400% - <b>Now 200%</b>)
- [x] Lucene.Net.Facet.Taxonomy.WriterCache.TestCharBlockArray.TestArray	(5498% - <b>Now 171%</b>)
- [ ] Lucene.Net.Util.TestAttributeSource.TestCaptureState	(4850% - <b>Now 1300%</b>)
- [ ] Lucene.Net.Util.TestBroadWord.TestPerfSelectAllBitsBroad	(4267% - <b>Now 733%</b>)
- [x] Lucene.Net.Util.TestFixedBitSet.TestAgainstBitSet	(2999% - <b>Now 26%</b>)
- [ ] Lucene.Net.Util.Automaton.TestBasicOperations.TestEmptyLanguageConcatenate	(2750% - <b>Now 300%</b>)
- [x] Lucene.Net.Util.TestRecyclingByteBlockAllocator.TestAllocate	(2333% - <b>Now 33%</b>)
- [x] Lucene.Net.Util.TestPackedInts.TestAppendingLongBuffer	(1597% - <b>Now 27%</b>)
- [ ] Lucene.Net.Util.TestIdentityHashSet.TestCheck	(1176% - <b>Now 863%</b>)
- [x] Lucene.Net.Util.TestPagedBytes.TestDataInputOutput	(1015% <b>Now 51%</b>)
- [x] Lucene.Net.Util.TestByteBlockPool.TestReadAndWrite	(1008% <b>Now 158%</b>)
- [x] Lucene.Net.Util.TestWAH8DocIdSet.TestAgainstBitSet	(895% <b>Now 67%</b>)
- [x] Lucene.Net.Util.TestPagedBytes.TestDataInputOutput2	(849% <b>Now 106%</b>)
- [ ] Lucene.Net.Util.TestBasicOperations.TestEmptySingletonConcatenate	(775%)
- [x] Lucene.Net.Util.TestBytesRefHash.TestSize	(762% <b>Now 87%</b>)
- [x] Lucene.Net.Util.TestOpenBitSet.TestAgainstBitSet	(720% <b>Now 155%</b>)
- [ ] Lucene.Net.Util.TestNumericUtils.TestRandomSplit	(708%)
- [x] Lucene.Net.Util.Fst.TestBytesStore.TestRandom	(681% <b>Now 98%</b>)
- [x] Lucene.Net.Util.Packed.TestEliasFanoSequence.TestAdvanceToAndBackToMultiples	(555% - <b>Now 131%</b>)
- [x] Lucene.Net.Util.TestOfflineSorter.TestSmallRandom	(555% - <b>Now 30%</b>)
- [x] Lucene.Net.Util.TestBytesRefHash.TestSort	(414% - <b>Now 73%</b>)
- [x] Lucene.Net.Util.TestBytesRefHash.TestGet	(343% - <b>Now 62%</b>)
- [x] Lucene.Net.Util.TestBytesRefHash.TestAddByPoolOffset	(331% - <b>Now 110%</b>)
- [x] Lucene.Net.Util.TestUnicodeUtil.TestCodePointCount	(294% - <b>Now 32%</b>)
- [ ] Lucene.Net.Util.Fst.TestFsts.TestRandomWords	(289%)
- [x] Lucene.Net.Util.TestBytesRefHash.TestFind	(284% - <b>Now 65%</b>)
- [x] Lucene.Net.Util.TestBytesRefHash.TestCompact	(273% - <b>Now 80%</b>)
- [x] Lucene.Net.Util.TestUnicodeUtil.TestUTF8toUTF32	(256% - <b>Now 34%</b>)
- [x] Lucene.Net.Util.TestOfflineSorter.TestIntermediateMerges	(242% - <b>Now 30%</b>)
- [x] Lucene.Net.Util.TestOpenBitSet.TestSmall	(188% - <b>Now 40%</b>)

---------------

> These tests were not apples-apples comparisons, the Java tests were run on an older and slower machine that was outclassed in RAM, CPU, and disk read/write speeds by the machine that was used to test in .NET. The percentage is the approximate value that was measured by the test frameworks, but is probably significantly lower than the difference using a proper benchmark on the same machine.

### BitSet vs BitArray

The `TestAgainstBitSet` test is slow in almost every test that utilizes it.

One potential reason for this is that we are using the .NET `BitArray` class and in Java Lucene was using a `BitSet`. While remapping to .NET APIs is the preferred way of porting, in this case we have classes with completely different behaviors. `BitArray` is a fixed size, and `BitSet` automatically expands as needed. To make `BitArray` expand, we need to reallocate it, and those extra allocations may be contributing to these tests being slow.

Note that J2N has [a C# implementation of `BitSet`](https://github.com/NightOwl888/J2N/blob/1ace2b3ad498501f9ea36bc277b353b54ddfc588/src/J2N/Collections/BitSet.cs) that would be acceptable to use instead of `BitArray` if this is indeed one of the contributors.

**Comment by bongohrtech** [comment]
I believe NUnit should have an overload for numeric types but when comparing type long this seems to take a very long time to resolve. Using an overload a == b seems to result in much faster performance. The same is true for byte comparison.

This as been added to the Assert.cs file which overloads AreEqual for long and byte

**Comment by bongohrtech** [comment]
Tests in T-U seem to have been resolved where there is the most delay. 
Adding the following line will force the tests to use the overloaded methods. 
using Debug = Lucene.Net.Diagnostics.Debug;

assertEquals in LuceneTestCase has also been modified to use the same equivalence checks

**Comment by NightOwl888** [comment]
@bongohrtech - Good find. There are several tests that are passing value types through `Assert.AreEqual(object, object)` in a tight loop, causing lots of box/unbox operations. And of course, this problem isn't limited to the `Lucene.Net.Util` namespace.

I have confirmed that changing this gets both T-U and U-Z projects to run in under 3.5 minutes, which were more like 11 minutes before.

We should aim to apply this fix on all of the projects starting with the longest running ones:

- `Lucene.Net.Tests._E-I`
- `Lucene.Net.Tests.Analysis.Common`
- `Lucene.Net.Tests.Codecs`
- `Lucene.Net.Tests._A-D`
- `Lucene.Net.Tests._J-S`

We can probably also consolidate some of the 5 Lucene.Net test projects that were broken up, which should help to speed up the overall time in Azure DevOps.
