### ISSUE TITLE
Method not found: 'System.IO.MemoryMappedFiles.MemoryMappedFile System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile

### ISSUE THREAD

**Issue by ondister** [apache/lucenenet#336]
Lucene.Net 4.8.0-beta00006
I have an error: Method not found: 'System.IO.MemoryMappedFiles.MemoryMappedFile System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(System.IO.FileStream, System.String, Int64, System.IO.MemoryMappedFiles.MemoryMappedFileAccess, System.IO.MemoryMappedFiles.MemoryMappedFileSecurity, System.IO.HandleInheritability, Boolean)'. 
with .net core 3.1 test project. This is  method from .net framework 4.8 and it has not System.IO.HandleInheritability parameter  in .net core 3.1

**Comment by NightOwl888** [comment]
We've updated the compilation symbols so they don't depend directly on the target framework:

```c#
            if (input.memoryMappedFile == null)
            {
                input.memoryMappedFile = MemoryMappedFile.CreateFromFile(
                    fileStream: fc, 
                    mapName: null, 
                    capacity: length, 
                    access: MemoryMappedFileAccess.Read,
#if FEATURE_MEMORYMAPPEDFILESECURITY
                    memoryMappedFileSecurity: null,
#endif
                    inheritability: HandleInheritability.Inheritable, 
                    leaveOpen: true); // LUCENENET: We explicitly dispose the FileStream separately.
            }
```

This makes the default disable the `memoryMappedFileSecurity` parameter unless the `FEATURE_MEMORYMAPPEDFILESECURITY` compilation symbol is added. The [Directory.Build.targets](https://github.com/apache/lucenenet/blob/b2f737de07242869819054642081337812488903/Directory.Build.targets) file maps the target framework to features for the entire solution.

There really doesn't seem to be any more to do here, so I am closing this issue.
