### ISSUE TITLE
Unwanted files being added to projects

### ISSUE THREAD

**Issue by nazjunaid** [apache/lucenenet#343]
Adding Lucene.Net via nuget is adding some unwanted files to our projects namely.

j2n-icon-100x100.png
LICENSE.txt

There there a reason why it needs to do this?

**Comment by TheBeardedLlama** [comment]
probably mistake in the packaging of the most recent release

should be easy to resolve with a quick PR

**Comment by nazjunaid** [comment]
Just had a dig around looks like it's coming from J2N

https://github.com/NightOwl888/J2N/blob/ee502ac09b9ea6b84ff36c2778665991cfe612ac/build/nuget.props

**Comment by TheBeardedLlama** [comment]
ah yeah

considering they're in beta, they could easily do a new release removing those I guess

**Comment by NightOwl888** [comment]
This has now been addressed in

* [J2N v2.0.0-beta-0010](https://github.com/NightOwl888/J2N/releases/tag/v2.0.0-beta-0010)
* [ICU4N v60.1.0-alpha.353](https://github.com/NightOwl888/ICU4N/releases/tag/v60.1.0-alpha.353)

To target Lucene.Net 4.8.0-beta00012 or lower, you will need to install

* [J2N v2.0.0-beta-0010](https://github.com/NightOwl888/J2N/releases/tag/v2.0.0-beta-0010) prior to installing Lucene.Net (or any assembly that depends on it)
* [ICU4N v60.1.0-alpha.353](https://github.com/NightOwl888/ICU4N/releases/tag/v60.1.0-alpha.353) prior to installing Lucene.Net.ICU (or any assembly that depends on it)
