### ISSUE TITLE
Refactor IndexSearcher

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#353]
IndexSearcher has 2 nested classes that are each being instantiated in a tight loop:

1. [`SearcherCallableNoSort`](https://github.com/apache/lucenenet/blob/ece6bea0a3c98961a77d7060b5615fccefabe725/src/Lucene.Net/Search/IndexSearcher.cs#L721-L768)
2. [`SearcherCallableWithSort`](https://github.com/apache/lucenenet/blob/ece6bea0a3c98961a77d7060b5615fccefabe725/src/Lucene.Net/Search/IndexSearcher.cs#L770-L832)

Each of these classes implements `ICallable<T>`, an interface that was carried over from Java. The closest match in .NET is `Func<T>`. Both classes (and their many member variables) can be eliminated and their `Call()` method placed in the inline body of `Func<T>`, which will eliminate the class instantiation per loop.

I suspect this will have a performance impact, but even if not this is a step away from Java and toward .NET.

`TaskSchedulerCompletionService.Submit(ICallable<T> task)` should be modified to accept a `Func<T>` and doesn't need to implement `ICompletionService<T>`.

We should also aim to factor out (and delete) `ICallable<T>` and `ICompletionService<T>` from Lucene.NET.

**Comment by jeme** [comment]
Enhancements like this are not really "mandatory" for a 4.8 release are they?...

If so, wouldn't it be better to put them to a 4.8.1 milestone? (I know there is a 4.8.1 java version as well, but perhaps the aim could include whatever that has in such case, alternatively it could be a 4.8.0+Optional milestone to indicate that if it makes it before the 4.8 that's fine, and if it doesn't then that's fine to.).

It's just to put more focus on closing the 4.8 release, (it would be to give a more clear picture of how far we are from that release)

**Comment by NightOwl888** [comment]
@jeme - Good point. The types involved are all internal, so this can technically be done at any point. I have changed the milestone to Future.

Also, after chewing on this a bit more, I don't think there is as much benefit as I thought. The classes might not be eliminated due to the fact we need the state passed into each thread. The best we can probably do is to change this from

```c#
runner.Submit(new SearcherCallableNoSort(@lock, this, m_leafSlices[i], weight, after, nDocs, hq));
```

to

```c#
runner.Submit(new SearcherCallableNoSort(@lock, this, m_leafSlices[i], weight, after, nDocs, hq).Call);
```

by changing the parameter of `Submit()` to a `Func<T>`. Although, there may be a cleaner option with `ParameterizedThreadStart`.

**Comment by rclabo** [comment]
Based on the Sept 24, 2020, I wonder if this one should be closed and not done.  If all affected methods are internal, and if the object instantiation in a tight loop can't be omitted then I'm not sure there is much benefit   And any benifit needs to be weighed against the downside. Converting the public API surface to follow .Net conventions is great, but for private methods, the benefit is less clear since any changes means that doing doing diff against a future java version and applying those diffs is more challenging.

**Comment by NightOwl888** [comment]
@rclabo

Agreed, this isn't worth the effort.
