### ISSUE TITLE
Replicator doesn't work

### ISSUE THREAD

**Issue by mypolat** [apache/lucenenet#382]
I have a project to run on **Linux** (Ubuntu 20.x). I am currently developing on **Windows**. I am using **4.8.0-beta00012** packages of "Lucene .Net". I want to do a **replication** process. I made use of this [document ](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Replicator/Http/replicator.md) for this. I followed all the steps. But the replication process does not react. "client.InfoStream" is empty. What am I missing?

Thank you for your interest.

_Server side:
.Net Core 3.1 Web Api_

Related Code:

**in Startup.cs**
```
            #region LuceneReplicator

            var replicationService = new ReplicationService(new Dictionary<string, IReplicator> { { ReplicationConsts.SHARD_NAME, new LocalReplicator() } }, ReplicationConsts.REPLICATION_ENDPOINT);

            app.Map(ReplicationConsts.REPLICATION_ENDPOINT, builder =>
            {
                builder.Run(async context =>
                {
                    await Task.Yield();
                    replicationService.Perform(context.Request, context.Response);
                });
            });

            #endregion
```

_Client side:
.Net Core 3.1 Hosted Service (Worker)_

Related Code:

```
public class ClientReplicator
    {
        private const string HANDLER_INDEX_DIR = "C:/LuceneIndexes/handler";
        private const string WORKING_PATH_DIR = "C:/LuceneIndexes/clientWorkDir";
        public async Task UpdateChecker()
        {
            await Task.Run(() =>
            {
                IReplicator replicator = new HttpReplicator("localhost", 5003, $"{ReplicationConsts.REPLICATION_ENDPOINT}/{ReplicationConsts.SHARD_NAME}");

                var handlerIndexDir = FSDirectory.Open(Path.GetFullPath(HANDLER_INDEX_DIR));
                var workingPath = Path.GetFullPath(WORKING_PATH_DIR);

                var client = new ReplicationClient(replicator,
                    new IndexReplicationHandler(handlerIndexDir, () => Notify()), new PerSessionDirectoryFactory(workingPath));

                //Now either start the Update Thread or do manual pulls periodically.
                client.UpdateNow(); //Manual Pull

                Console.WriteLine(client.InfoStream.ToString());
            });
        }

        public static bool Notify()
        {
            Console.WriteLine("Update!");
            return true;
        }
    }
```

**Comment by NightOwl888** [comment]
I am not sure if this will completely solve the problems you are seeing, but I have spotted 2 issues that are definitely obstructing your path to a solution.

Analyzing the [Lucene.Net.Replicator.AspNetCore](https://github.com/apache/lucenenet/tree/146d7d052db27d78726697c7c777915abceede25/src/dotnet/Lucene.Net.Replicator.AspNetCore) project might also prove helpful.

### InfoStream

`InfoStream` acts like any other stream. It doesn't collect information, but it passes information along to another source. 

For performance reasons, the `ReplicationClient.InfoStream` property uses `InfoStream.NO_OUTPUT` by default. To receive `InfoStream` messages, you need to set it to another `InfoStream` implementation. For example, to write to the console output, you would need to set it an instance of `TextWriterInfoStream` that wraps `Console.Out`.

```c#
    var client = new ReplicationClient(replicator,
        new IndexReplicationHandler(handlerIndexDir, () => Notify()), new PerSessionDirectoryFactory(workingPath));

// For optimal performance in production, InfoStream should not be enabled in the release.
// Although, you may wish to add a configuration switch to your application instead of using #if DEBUG
// to make troubleshooting easier in a release build.
#if DEBUG
    // Write any InfoStream messages to the console output
    client.InfoStream = new TextWriterInfoStream(Console.Out);
#endif
```

And of course, this line will still do nothing, so it can be removed:

```c#
Console.WriteLine(client.InfoStream.ToString());
```

### Machine-Independent Paths

Linux won't recognize the paths you have setup as constants. An approach you could use to create machine-independent paths is to use the [Environment.GetFolderPath](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netcore-3.1#System_Environment_GetFolderPath_System_Environment_SpecialFolder_) method.

```c#
var commonApplicationDataDir = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);

var handlerIndexDir = Path.Combine(commonApplicationDataDir, "LuceneIndexes/handler");
var workingPathDir = Path.Combine(commonApplicationDataDir, "LuceneIndexes/clientWorkDir");
```

See [Environment.SpecialFolder Enum](https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=netcore-3.1) for additional options.

**Comment by mypolat** [comment]
Thank you. As you suggested, I get directories from environment enums now.

I understood my problem. I applied the solution and it was fixed. The problem was that the **LocalReplicator** I used in Startup and the **LocalReplicator** I indexed the document was not common. I realized it must be common. When I defined LocalReplicator as Static, the problem was solved. I was able to replicate. (Is this a correct determination? And a correct solution?)

But now I have caused another problem. My API takes the index name from outside. The user can dynamically index. If I want to add a new record to the same index, I get the error "cannot compare IndexCommits from different Directory instances". I re-create IndexWriter and directory for each request.

What can I do to overcome this problem and provide editing?

**Comment by jeme** [comment]
First and foremost, you probably need to describe your scenario a bit more so we know what you are trying to achieve over all, as it stands there is a few things that goes against common recommendations. Also for what is described in https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Replicator/Http/replicator.md it really only provides the most basic example so that people can get started using the replicator.

I don't know if this crude sample can help you: https://github.com/jeme/LuceneNet.ReplicatorSample
It uses a class called DataIngestSimulator to simulate changes over time to each index. (An update to a random number of documents each 30 seconds).

When you say that the user can dynamically index, what do you exactly mean?... Are you simply trying to provide the users with Real-time search, as in the user may update a document/an entity of some sort which you then want to index and make available right away? or are you referring to something else?

You should avoid recreating your Index writers unless they experience an error (e.g. OutOfMemmoryExceptions) and share them across all indexing, (That is one writer Per index in your case).

**Comment by mypolat** [comment]
> First and foremost, you probably need to describe your scenario a bit more so we know what you are trying to achieve over all, as it stands there is a few things that goes against common recommendations. Also for what is described in https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Replicator/Http/replicator.md it really only provides the most basic example so that people can get started using the replicator.
> 
> I don't know if this crude sample can help you: https://github.com/jeme/LuceneNet.ReplicatorSample
> It uses a class called DataIngestSimulator to simulate changes over time to each index. (An update to a random number of documents each 30 seconds).
> 
> When you say that the user can dynamically index, what do you exactly mean?... Are you simply trying to provide the users with Real-time search, as in the user may update a document/an entity of some sort which you then want to index and make available right away? or are you referring to something else?
> 
> You should avoid recreating your Index writers unless they experience an error (e.g. OutOfMemmoryExceptions) and share them across all indexing, (That is one writer Per index in your case).

The project you created has been very useful for me, thank you.  I completed my shortcomings from there. My project is working as I want right now.

So is the scenario below possible with Lucene .Net?

A master, slave B and C
B master, slave A and C
C master, slave A and B
There will be always 2 copies.

**Comment by jeme** [comment]
Yes that will certainly be possible, but it's up to you to implement the details.

The obvious approach here would be to have a configuration which defines what indexes a node are master of and which indexes it should replicate from a different master.
