### ISSUE TITLE
Distributed Search

### ISSUE THREAD

**Issue by mypolat** [apache/lucenenet#397]
Hi all,
Is there a feature in Lucene .Net that can combine query results from different servers into a single result? We need to then combine results from multiple machine and present it to the user.
Version 3.0.3 has DistrubutedSearch feature, but I couldn't see it in 4.8.x. How can I do distributed search?
Yours truly.

**Comment by mypolat** [comment]
Hello, can you help me?

> Hi all,
> Is there a feature in Lucene .Net that can combine query results from different servers into a single result? We need to then combine results from multiple machine and present it to the user.
> Version 3.0.3 has DistrubutedSearch feature, but I couldn't see it in 4.8.x. How can I do distributed search?
> Yours truly.

**Comment by NightOwl888** [comment]
>  In general, you would be better off asking user questions [on StackOverflow](https://stackoverflow.com/questions/tagged/lucene.net) or the [User Mailing List](https://lucenenet.apache.org/contributing/mailing-lists.html#users-user) than here.

Lucene is a low-level search library that gives you the tools to build a higher-level search engine, but itself is not a search engine, thus it does not contain any distributed features out of the box. Some distributed 3rd party search engines that are built on Lucene/Lucene.NET:

- [NCache Distributed Lucene](https://www.alachisoft.com/ncache/distributed-lucene.html)
- [SOLR Index Sharding](https://lucene.apache.org/solr/guide/6_6/distributed-search-with-index-sharding.html) (legacy)
- [SolrCloud](https://lucene.apache.org/solr/guide/6_6/solrcloud.html#solrcloud)
- [Elastic Search](https://www.elastic.co/elasticsearch/)

If you prefer to roll your own solution, Lucene.NET 4.8.0 has a [replicator module](https://lucenenet.apache.org/docs/4.8.0-beta00013/api/replicator/Lucene.Net.Replicator.html) that might get you part of the way there.

### Lucene.Net.DistributedSearch

I searched the email archives and discovered the following thread. It seems that `Lucene.Net.DistributedSearch` was brought over from Lucene.NET 2.9.4. It was a contributed feature that was never actually ported over from Lucene.

http://markmail.org/message/acd6f3rsw626ysvv

[Distributed Search Source Code](https://github.com/apache/lucenenet/tree/3.0.3/src/contrib/DistributedSearch)

There is a problem with the way `Lucene.Net.DistributedSearch` is currently implemented that is blocking if from moving forward - it requires many objects to be serializable, which is no longer considered to be a good practice. See [LUCENENET-502 (comment)](https://issues.apache.org/jira/browse/LUCENENET-502?focusedCommentId=16905862&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16905862). If we were to revive such a feature (and frankly, I am not sure it belongs in Lucene.NET), it would be better to come up with a new design that is based on a more cloud-friendly technology and an alternative to using .NET's binary serialization.
