### ISSUE TITLE
Lucene Replication - Geting revision from replicator (local) and handler (remote) 

### ISSUE THREAD

**Issue by yashhema** [apache/lucenenet#401]
I am studying Lucene replication for my understanding .  Lets consider case server A is the master and server B is the slave.
I have indexA1, indexA2 on server A which I want to replicate to Server B
 Process
-- On Server A - Any time i make changes to index A1 or indexA2 , i call Replicator.Publish(new IndexRevision(_writer))  for the corresponding index. Here Replicator represents local replicator (there will be 2 local replicator - as I want to replicate 2 indexes)

-- On  Server B - I will create a replication client , passing it to http replicator, IndexReplicationHandler and persessionfactor , and then I can ask replicationclient to get data from server A  (as i have 2 indexes to replicate - I will start 2 clients) .

Question -
1  -- Is my understanding correct.

2   -- How can i know the current status of replication , i thought , I can use the field = Version , which is present in both localreplicator and IndexReplicationHandler , and I can know if  the replicated copy is at the same version as master copy, but the field is private -- Is there any reason for keeping it private  

3   -- To keep things simple, say I only do batch updates in server A , i manually start the replication on ServerB (with updatenow call) , how can I know that replication copy has finished.

I think , having point 2 and 3 , will give greater control to the developer in planning his replication strategy (as well as how to handle failover/recovery from failover better)

regards

**Comment by jeme** [comment]
1) Sounds about right

2) Since your passing a IReplicationHandler to the client, where IndexReplicationHandler is just the built-in implementation, see: CurrentVersion : https://github.com/apache/lucenenet/blob/4e66181e702db9a0849a26a86361a8fc1e796c3f/src/Lucene.Net.Replicator/ReplicationClient.cs#L496

3) Do the batch update and wait with publishing a revision till your done, on server B the IndexReplicationHandler takes a Func<bool?> as a last parameter in the constructor, this is called as the last thing in the replication process.

If you require a tighter integration or perhaps more insight to when a replication starts and ends on server B, or to expose additional information. You can utilize a decorator pattern and simply delegate to the IndexReplicationHandler.

E.g.

```CSharp
public class MyIndexReplicationHandler : IReplicationHandler
{
    private readonly IReplicationHandler innerHandler;

    public string CurrentVersion => innerHandler.CurrentVersion;

    public IDictionary<string, IList<RevisionFile>> CurrentRevisionFiles => innerHandler.CurrentRevisionFiles;
    
    public MyIndexReplicationHandler(IReplicationHandler innerHandler)
    {
        this.innerHandler = innerHandler;
    }

    public void RevisionReady(string version, IDictionary<string, IList<RevisionFile>> revisionFiles, IDictionary<string, IList<string>> copiedFiles, IDictionary<string, Directory> sourceDirectory)
    {
        //TODO: Do something before replication takes place.
        innerHandler.RevisionReady(version, revisionFiles, copiedFiles, sourceDirectory);
        //TODO: Do something after replication takes place.
    }
}
```

**Comment by yashhema** [comment]
Thanks , for the explanation . How can we get the revision from server A LocalReplicator (ie the entity for which we are replicating data) . I looked in the code for it  -- **lucenenet/src/Lucene.Net.Replicator/LocalReplicator.cs**
I dont see a way to get version from it.
**### private volatile RefCountedRevision currentRevision;**
The above field is marked private .
Can you please explain how to get this value

**Comment by jeme** [comment]
You can get that from the Revision you publish. So create that outside the call to publish and assign it to a variable, then you can read it's Version property.

**Comment by yashhema** [comment]
Perfect thanks for your inputs. Now I think i have got the required understanding, now let me see , if I can use it to build something.
