### ISSUE TITLE
remove unnecessary locks from FacetsConfig

### ISSUE THREAD

**Issue by eladmarg** [apache/lucenenet#409]
FacetsConfig already contains ConcurrentDictionary container,
there is no need for locks, especially on GetDimConfig

**Comment by NightOwl888** [comment]
It looks like we no longer have concurrency issues in Lucene.Net.Facet in `TestDirectoryTaxonomyWriter::TestConcurrency()` or `TestSearcherTaxonomyManger::Test_Directory()`, so the safe bet is not to alter this any further.
