### ISSUE TITLE
CLI Documentation issue - environment variable token not replaced

### ISSUE THREAD

**Issue by Freya702** [apache/lucenenet#416]
The issue is on the CLI docs here https://lucenenet.apache.org/docs/4.8.0-beta00013/cli/index.html

The `[EnvVar:LuceneNetVersion]` didn't get replaced during the build and needs to be fixed. It should list the current lucene version being built, like: `dotnet tool install lucene-cli -g --version 4.8.0-beta00013`

---

## Original issue: 

I'm trying to install Lucene.net CLI

When I run the command dotnet tool install lucene-cli -g --version [EnvVar:LuceneNetVersion] I get an error: Specified version '[EnvVar:LuceneNetVersion]' is not a valid NuGet version range.

When I run the command dotnet --list-runtimes, I find that I have Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] while the prequisite is .NET Core 3.1.0 Runtime. I suppose that it's compatible, but I'm not sure.

I don't know how to fix this.
https://stackoverflow.com/questions/66107372/installing-lucene-net-cli?noredirect=1#comment116885324_66107372

**Comment by Shazwazza** [comment]
This is a documentation build issue. `[EnvVar:LuceneNetVersion]` is a token that should have been replaced during the docs build. 

Please use a real version number here instead like `4.8.0-beta00013`

I'll try to get those docs fixed soon.
