### ISSUE TITLE
Hunspell affixes' file parsing corrupts some affixes' conditions

### ISSUE THREAD

**Issue by SergeyKotyushkin** [apache/lucenenet#418]
Hello!

Our hunspell aff file contains some rules for suffixes and prefixes that corrupt at the parsing.
For example:
```
SFX AA a b [c]d
```

The condition `[c]d` is a correct regex expression but this rule does not work.
The prblem is found in the hunspell dictionary class in the ParseAffix method ([place in code](https://github.com/apache/lucenenet/blob/f5cca0b1a7c855f2fe44a5cdd27763aab7acdf22/src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs#L463)).

We can see that if affix's condition starts with `[` and not ends with `]` then the `]` adds at the end of condition. So the condition become incorrect regex expression `[c]d]`.

Maybe there the `!condition.EndsWith("]", StringComparison.Ordinal)` check should be replaced with the `condition.IndexOf("]", StringComparison.Ordinal) == -1` check. But I don't know about reasons of current version code. So I can be wrong.

**Comment by NightOwl888** [comment]
Thanks for the report.

Hunspell was one of the most difficult analyzers to port to .NET. As a result it is not clear if this problem is a bug caused during the port or if this is a preexisting Lucene bug. Could you provide a unit test or other working code example demonstrating the problem so we can port it back to Java to check whether this bug also exists in Lucene?

**Comment by SergeyKotyushkin** [comment]
> Thanks for the report.
> 
> Hunspell was one of the most difficult analyzers to port to .NET. As a result it is not clear if this problem is a bug caused during the port or if this is a preexisting Lucene bug. Could you provide a unit test or other working code example demonstrating the problem so we can port it back to Java to check whether this bug also exists in Lucene?

If you allow I write scenario right here in comment.
_condition-issue-418.aff_
```
SET UTF-8
TRY esianrtolcdugmphbyfvkwzESIANRTOLCDUGMPHBYFVKWZ’

PFX A Y 1
PFX A 0 re [w]o

SFX B Y 1
SFX B 0 ed [r]k
```

_condition-issue-418.dic_
```
1
work/AB
```

_TestConditionIssue418.cs_ (it is based on [TestCondition.cs](https://github.com/apache/lucenenet/blob/f5cca0b1a7c855f2fe44a5cdd27763aab7acdf22/src/Lucene.Net.Tests.Analysis.Common/Analysis/Hunspell/TestCondition.cs))
```cs
public class TestConditionIssue418 : StemmerTestBase
{
    [OneTimeSetUp]
    public override void BeforeClass()
    {
        base.BeforeClass();
        Init("condition-issue-418.aff", "condition-issue-418.dic");
    }

    [Test]
    public virtual void TestStemming()
    {
        AssertStemsTo("rework", "work");
        AssertStemsTo("worked", "work");
    }
}
```

Both these test fail.
But if we change [here](https://github.com/apache/lucenenet/blob/f5cca0b1a7c855f2fe44a5cdd27763aab7acdf22/src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs#L463) the condition
```cs
condition.StartsWith("[", StringComparison.Ordinal) && !condition.EndsWith("]", StringComparison.Ordinal)
```
on another one
```cs
condition.StartsWith("[", StringComparison.Ordinal) && condition.IndexOf("]", StringComparison.Ordinal) == -1
```
then they work.

**Comment by NightOwl888** [comment]
Thanks. The test looks good, but it seems you didn't attach the `condition-issue-418.aff` and `.condition-issue-418.dic` files.

**Comment by SergeyKotyushkin** [comment]
> Thanks. The test looks good, but it seems you didn't attach the `condition-issue-418.aff` and `.condition-issue-418.dic` files.

Yes, I didn't attach them but I wrote their content right in my comment.

**Comment by NightOwl888** [comment]
Great. I ran the tests in Lucene 4.8.0 and they fail, however in Lucene 8.2.0, they succeed. I checked the source, at least as far back as Lucene 4.10.4 the [line in question](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/4.10.4/lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java#L503) was changed to use `IndexOf` just as you have suggested.

So, if we upgrade `Lucene.Net.Hunspell` to 4.10.4 as I proposed in #419, we will patch this problem automatically.
