### ISSUE TITLE
Best way to setup dev machine for LuceneNet website edits

### ISSUE THREAD

**Issue by rclabo** [apache/lucenenet#447]
@Shazwazza 

Hi Shannon,

I'd like to make the following small addition to the home page of the Lucene.net website give developers more information about the Lucene 4.8 version which will hopefully give them the confidence to give it a try.  Specifically I'd like to add something similar to:

## Latest Version - Lucene 4.8 Beta

- The beta version is extremely stable
- Has more than 7000+ passing unit tests
- Integrates well with .Net 5.0 
- Supports NetStandard 2.0 and NetStandard 2.1
- Supports with .Net Framework 4.5.1+
- Some developers already use it in production environments

It's a pretty easy add but I need to first configure my dev machine for it.  Initially I just downloaded the a zip file of the master at https://github.com/apache/lucenenet-site/ to check it out.  Looks like a static website, IIS not required, and I didn't see any Visual Studio project files in the folder structure.  So I just double clicked the index.html file to view it in the browser but it doesn't quite render properly.  On my machine it looks like this below (Notice the missing blue banner):

![mine](https://user-images.githubusercontent.com/6945499/112213491-8388e500-8bf4-11eb-9bb5-3fa45ae05429.png)

Whereas the actual site looks like this:

![expected](https://user-images.githubusercontent.com/6945499/112213604-a3b8a400-8bf4-11eb-9322-5a6907490ceb.png)

So I may be mistaken and it may not be designed to run from the desktop like this.  Any pointers on how I can setup a dev environment locally to do some changes to the index.html file?

**Comment by NightOwl888** [comment]
@rclabo

The [documentation for building the website and API docs sites](https://lucenenet.apache.org/contributing/documentation.html) gives some info about how all of this works, but it would be great for someone to poke holes in that documentation to see how well it holds up to scrutiny.

1. Updates to the website happen in the pre-build stage in this repo. See [apidocs](https://github.com/apache/lucenenet/tree/921ad114b43f5e0cd565c54fb88667fa027d6708/websites/apidocs) and [site](https://github.com/apache/lucenenet/tree/921ad114b43f5e0cd565c54fb88667fa027d6708/websites/site).
2. The documentation is then "assembled" using the DocFx build engine.
3. The main/API sites are then updated by copying and pasting the files into https://github.com/apache/lucenenet-site/, which is setup to serve the site live.

The build process serves the site up on your localhost so you can preview it as you make changes.

@Shazwazza has been working on getting more of this process automated (like setting it up so accepting a PR automatically builds/deploys the site), but we are not quite there yet.

> NOTE: It would be great if we could come up with a way to be able to "preview" pages more quickly than to go through the drawn out build process, if it is possible. Consider that a feature request.

> NOTE: I am currently updating that document because we have switched over to using mini-sites for the API docs, which each have their own DocFx configuration file and the document still only mentions the common configuration file that we used when there was one site.

**Comment by Shazwazza** [comment]
@rclabo The should still be reasonably accurate. With the normal Lucene.Net git source cloned to your machine you can just run this via powershell `.\websites\site\site.ps1 -ServeDocs`. To push this live is done manually now but happy to do that if you just start with a PR for updating the website files.

As @NightOwl888 mentioned I'm still working on automating the deployment of this which is now relying on Infra to get this done https://issues.apache.org/jira/browse/INFRA-21453?filter=-2 . @NightOwl888 do you know any tricks to get them to respond? If that task can be completed, deploying the website is very easy.

**Comment by NightOwl888** [comment]
> @NightOwl888 do you know any tricks to get them to respond? If that task can be completed, deploying the website is very easy.

The only "trick" I know is to keep nagging :unamused:. Crude but effective.

**Comment by rclabo** [comment]
Awesome that all sounds great and was just what I needed to know.  Especially 
>"The build process serves the sites up on your localhost so you can preview them as you make changes." 

and 

>"With the normal Lucene.Net git source cloned to your machine you can just run this via powershell .\websites\site\site.ps1 -ServeDocs. To push this live is done manually now but happy to do that if you just start with a PR for updating the website files." 

Awesome.  It'll be a couple days till I can do this. but I now feel equiped to get make the change, preview it on my machine and submit a PR.  Awesome.

**Comment by NightOwl888** [comment]
> As @NightOwl888 mentioned I'm still working on automating the deployment of this which is now relying on Infra to get this done https://issues.apache.org/jira/browse/INFRA-21453?filter=-2 . @NightOwl888 do you know any tricks to get them to respond? If that task can be completed, deploying the website is very easy.

I replied to the JIRA issue, but given the fact that they wouldn't even generate a temporary PAT for us to migrate our issues from JIRA to GitHub, I don't think it is likely they will allow this. We should put our heads together, do research, and come up with alternatives in case this doesn't happen.

**Comment by Shazwazza** [comment]
Thanks, at least you got a reply :) They have set this up for other projects (i.e. Apache Arrow) though, they've even slightly documented it: https://infra.apache.org/github-actions-secrets.html

**Comment by NightOwl888** [comment]
Well, that looks more promising. I guess they are getting tons of requests for these so they are allowing in certain scenarios.

**Comment by rclabo** [comment]
I was able to edit the LuceneNet website home page to include some new content and preview it on my machine and submitted a PR for a few changes.  Progress.  One thing I couldn't do was modify the css because when I made changes to the main.css file my local git didn't notice the changes.  

I see the file is located locally at lucenenet/websites/site/_site/styles/main.css  I wonder if it's the leading underscore on _site that is causing the git to not see the changes to the file?  Not sure. Any suggestions on how I can edit the style sheet so that I can affect visual changes that I can see locally and include in a future PR?

**Comment by rclabo** [comment]
Also: 
I ran into one other issue.  My local branch I'm working in is 'Documentation_work'.  When I build and serve the website by running the powershell scripst

 ./websites/site/site.ps1 -ServeDocs 

The command appears to be working and serves the website at http://localhost:8081/   but errors are showing up in powershell window  that say things like 

>[21-03-26 07:38:02.951]Info:[BuildCommand.BuildCore.Build Document.Load.ConceptualDocumentProcessor](index.md)For git repo <C:/Users/Ron/source/repos/lucenenet>, can't find remote branch in this repo and fallback to use local branch [Documentation_work]: fatal: no upstream configured for branch 'Documentation_work'  

I have a remote for my master but it appears to want me to setup a remote for my current dev branch but I'm not sure what it wants the remote set to for that branch.  How do I fix that?

**Comment by Shazwazza** [comment]
Hi, the _site is the build output of the website so is ignored by git. The source files for the website are here: https://github.com/apache/lucenenet/tree/master/websites/site as for the CSS and layout files, docfx works based on templates and overrides. By default it has it's own internal template including CSS and then we have a custom template to override certain aspects of that. Our custom template is here https://github.com/apache/lucenenet/tree/master/websites/site/lucenetemplate and our custom styles are here https://github.com/apache/lucenenet/tree/master/websites/site/lucenetemplate/styles

**Comment by Shazwazza** [comment]
DocFx requires an upstream git repository because it it queries for git information and current branch information to determine how things like "Improve this doc" buttons work (among other things especially when building source code docs)

**Comment by rclabo** [comment]
Thank you, that help a lot.  So I guess that means that DocFx is looking at my current git branch.  If my current git branch is one that I'm working in to make DocFx template or layout changes, lets say it called Working_Branch what should I set at the upstream repository to.  Should the upstream for that branch be  https://github.com/apache/lucenenet.git just like for master?

**Comment by Shazwazza** [comment]
Yeah normally you'd have the upstream git repo set to  https://github.com/apache/lucenenet.git and then your branches would be tracked to push/merge with the same corresponding name. Depending on what name you've configured your upstream repo to be (most times its `origin`) you can see how these branches are tracked by: `git remote show origin`. Guess it depends on how you use and configure git. I just use [Git Extensions](https://github.com/gitextensions/gitextensions) UI which takes the guess work out of all of this :)

**Comment by rclabo** [comment]
Thanks.  I'm still a newbie with git and have a lot to learn.

**Comment by rclabo** [comment]
My local branch is  'Documentation_work' and when I had it checked out I tried to run the same command I do for my master which is

`git remote add upstream  https://github.com/apache/lucenenet.git`

It came back with this error "error: remote upstream already exists."  So I guess I'm confused, can you shed any light on why this error?

**Comment by NightOwl888** [comment]
Remotes are local references to remote repositories. They exist in the local configuration of your copy of the repository.

You can view a list of all of the remotes by using the command

```
git remote
```

Or, even better, you can see the URLs of the remotes

```
git remote -v
```

Do note it is possible to set up a remote to pull from one repo and push to another (hence the 2 entries for each remote name).

But the bottom line is, if a remote already exists in your local repository that maps it to a remote one, there is no need to add it again. From that point, you can use its name.

> Do note using remotes is only a shortcut to make commands simpler - you could just as well use URLs to specify which repository to push to, fetch from, or pull from.
>
> Also, a remote exists at the top level of the repository, so you can use it for any number of branches.

**Comment by rclabo** [comment]
That all makes good sense.  So I wonder if the reason the powershell script is [complaining](https://github.com/apache/lucenenet/issues/447#issuecomment-808489721) is because I named mine upstream rather then origin.  I wonder that because the powershell script error said
>can't find remote branch in this repo

and Shannon @Shazwazza  mentioned that the the remote is often named origin.  

Or maybe the error is saying that I literally need a branch on the remote that is the same as my branch name.  But if that's the case I don't see how I can solve error since there is no way for me to create a branch on the remote repository at https://github.com/apache/lucenenet.git

**Comment by NightOwl888** [comment]
> [21-03-26 07:38:02.951]Info:BuildCommand.BuildCore.Build Document.Load.ConceptualDocumentProcessorFor git repo <C:/Users/Ron/source/repos/lucenenet>, can't find remote branch in this repo and fallback to use local branch [Documentation_work]: fatal: no upstream configured for branch 'Documentation_work'

> I wonder if the reason the powershell script is complaining is because I named mine upstream rather then origin. I wonder that because the powershell script error said
>
> > can't find remote branch in this repo

Okay, it sounds like you haven't configured a remote for your specific branch. Assuming you have `Documentation_work` checked out and you want to use the remote named `upstream`:

```
git branch --set-upstream-to=upstream/foo
```

Reference: https://stackoverflow.com/a/2286030

Note it is possible to have a different remote and local name, but I have never done it because of the confusion it would cause me.

I have no idea why the script would trigger that message, though. It doesn't seem to be doing anything with Git at all.

**Comment by NightOwl888** [comment]
It seems the original question has been answered and the original task has been completed in #454, so I am closing this.
