### ISSUE TITLE
Fetching a docvalue from the index

### ISSUE THREAD

**Issue by jregnier** [apache/lucenenet#477]
I am trying to figure out a way to fetch a binary docvalue from the index but I can't find anything online, Any suggestions on how to achieve this? Any help with this would be much appreciated. Thanks

**Comment by jregnier** [comment]
Hello again, So I think I'm getting closer lol, seems like the way to go is to create a custom ICollector. Below is what I have so far. Am I on the right track so far?

`    public class MyCollector : ICollector
    {
        private readonly OpenBitSet _bits;
        private int _docBase;
        private BinaryDocValues _docValues;
        private HashSet<string> _values;

        public MyCollector(OpenBitSet bits)
        {
            _bits = bits ?? throw new ArgumentNullException(nameof(bits));
            _values= new HashSet<string>();
        }

        public bool AcceptsDocsOutOfOrder => true;

        public void Collect(int doc)
        {
            _bits.Set(doc + _docBase);

            if (_docValues== null)
            {
                return;
            }

            var byteRef = new BytesRef();
            _docValues.Get(doc, byteRef);
            _values.Add(byteRef.Utf8ToString());
        }

        public void SetNextReader(AtomicReaderContext context)
        {
            _docValues = context.AtomicReader.GetBinaryDocValues("the_value");
            _docBase = context.DocBase;
        }

        public void SetScorer(Scorer scorer)
        {
            // We don't care about the score.
        }
    }`

**Comment by rclabo** [comment]
You might try taking a look at the unit tests.  For example [this code ](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Tests/Index/Test2BBinaryDocValues.cs#L88) may prove helpful.  For questions that are not an issue with the code or docs, it's best to post it on StackOverflow with a Lucene.net tag.  Sorry I didn't see your question here earlier.

**Comment by rclabo** [comment]
Thanks.  We'd love to update the documentation to be more helpful.  Could you write up what you think it should be and post it here  with code sample and I can see if I can get it added to the docs?
