### ISSUE TITLE
question - large size recommendation?

### ISSUE THREAD

**Issue by ensemblebd** [apache/lucenenet#489]
Hello.

I'm planning to use this for a massive amount of documents (millions).
And currently using RAMDirectory with a background FSDirectory sync operation on an interval to persist a `Queue<Document>`.

Would you recommend splitting documents by `<T>` _(ex. Addresses, Orders, Products)_ into separate directories to keep the system fast, or would 10 x 100,000 per `<T>` not be an issue rolled into a single FSD?

Trying to plan ahead on theory. Thank you!

**Comment by eladmarg** [comment]
this strategy called sharding, it's better to split the data by your logic and how the users query it.
for example, if you have geolocation users and they using data most of the time for one country, 
so you create an index for all new york and another one for new jersey.

if a user queries more than one location, you run both of the queries in parallel and aggregate the result.

**Comment by ensemblebd** [comment]
Thank you!  I hadn't thought of it in that perspective. 
Will need to rethink what chunks I could fashion out of which data parts appropriately.
