### ISSUE TITLE
QueryParse is incorrect when parsing NOT 

### ISSUE THREAD

**Issue by vucuongkg** [apache/lucenenet#493]
Hello,
I am changing from Lucene.net 3.x to Lucene.net 4.0.
I have found that behavior has changed when paring query.
I have attached 2 images that show different result with same input

![Screenshot_145](https://user-images.githubusercontent.com/6039359/121838080-3606aa80-cd01-11eb-949a-7ea8e82f1042.png)
![Screenshot_144](https://user-images.githubusercontent.com/6039359/121838082-3737d780-cd01-11eb-80e4-211a9d996e60.png)

It make return result different
Could you please check it?

**Comment by NightOwl888** [comment]
Thanks for the report. Could you please confirm that you are using the Classic `QueryParser`?

Also, could you please provide enough code (either a unit test or a console app) so we can run it to see this behavior?

Do note that the query parser is set up to be culture-sensitive based on the current thread by default. To override, you must set the `Locale` property of the `QueryParser` class.

**Comment by rclabo** [comment]
It's hard to tell, but for the search phrase is it specified as "Variant1 - Variant2" or "Variant1 -Variant2" ?  If the former then I suspect what you are experiencing is a bug in 3.x that was fixed in 4.x because having a space between the - and the term should not cause the term to be negated.

**Comment by vucuongkg** [comment]
I'm sorry for missing some info
Input: Variant1 - Variant2 (has space)
Output

Version 3.x: +_content:variant1 -_content:variant2 (NOT => -)
Version 4.0: +_content:variant1 +_content:variant2 (NOT => +, it should be -)

I will try again with sample console app using C#.

**Comment by vucuongkg** [comment]
> Thanks for the report. Could you please confirm that you are using the Classic `QueryParser`?
> 
> Also, could you please provide enough code (either a unit test or a console app) so we can run it to see this behavior?
> 
> Do note that the query parser is set up to be culture-sensitive based on the current thread by default. To override, you must set the `Locale` property of the `QueryParser` class.

Yes, version 4.0, I know that there are some changes .
I am using QueryParser class in  Lucene.Net.QueryParsers.Classic

**Comment by vucuongkg** [comment]
Hello, 
I have checked that and I am pretty sure I was correct.
You can check images below
![Screenshot_149](https://user-images.githubusercontent.com/6039359/121992318-9a8e3c00-cdcb-11eb-8891-1197dccd6e72.png)
![Screenshot_148](https://user-images.githubusercontent.com/6039359/121992321-9c57ff80-cdcb-11eb-96fc-a611240d478a.png)

I have created repository:
https://github.com/vucuongkg/Lucene.Net-QueryParse

Please check it, thanks.

**Comment by vucuongkg** [comment]
Ping @NightOwl888 , ;)

**Comment by rclabo** [comment]
If you take a look at the [documentation](https://lucene.apache.org/core/4_8_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#- ) for 4.8 you will see that it shows the minus sign next to the term or phrase with no space between them.   The example provided is "jakarta apache" -"Apache Lucene".  Again, I think you are witnessing a bug fix.  if you want the term or phrase negated you should remove the space between the minus sign and the term or phrase.

As further evidence, it's worth  noting that the lucene query syntax is very similar to that used by google.  And in google if you search for `Taiwan - history` you will see that the 2nd entry contains the word history 
![image](https://user-images.githubusercontent.com/6945499/122772213-22b18d00-d275-11eb-9187-17f7c64554e1.png)


but if you search for `Taiwan -history`  you will see that the results containing the word history have been removed.

![image](https://user-images.githubusercontent.com/6945499/122772412-5987a300-d275-11eb-9133-38bac88abb46.png)

So what you are experiencing in Lucene 4.8 isn't a bug in 4.8 it's a fix of a bug that existed in 3.x

**Comment by vucuongkg** [comment]
Hello @rclabo 
Thanks you so much for your reply, really detail and clear.
So, I close this.
