### ISSUE TITLE
New .cfs files created everytime I add to index

### ISSUE THREAD

**Issue by fjam** [apache/lucenenet#505]
On initial load of my application I add data into my Lucene index:

```
using (StandardAnalyzer analyzer = new StandardAnalyzer(LuceneVersion.LUCENE_48))
{
    using (IndexWriter writer = new IndexWriter(Directory)
    {

        Document doc = new Document();
    
        doc.Add(new TextField("Id", Id.ToString(), Lucene.Net.Documents.Field.Store.YES))
        doc.Add(new TextField("Symbol", Symbol, Lucene.Net.Documents.Field.Store.NO))
        doc.Add(new TextField("Channel",  Channel, Lucene.Net.Documents.Field.Store.NO))
    
        writer.AddDocument(doc);
        writer.Commmit();
    }
}
           
```   
This creates a few files (_0.cfe, _0.cfs ...) in the index directory.

Now when I add need to add a new index to Lucene with the same Model (Id, Symbols, Channel) it creates a new set of files (_1.cfe, _1.cfs ...) in the index directory without removing the _0.cfs... files.

**Comment by fjam** [comment]
I am using Lucene.NET version 4.8.0-beta00014

**Comment by rclabo** [comment]
Yep, that's the way Lucene.NET and Lucene works.  Each of these sets of files is called a segment.  Initially in your case there is one segment, the _0 segment, and then when you add another doc and commit there is a 2nd segment, the _1 segment.  If you want to learn more google about lucene and segments.  There is lots of info online.

**Comment by fjam** [comment]
I have a process running where there will be 1000s of documents being indexed a day (at different times). This way there will be 1000s of new .cfs files in my directory.

**Comment by fjam** [comment]
Is that correct way? or is there a way to merge these .cfs files together?

**Comment by rclabo** [comment]
Inserting 1000s of docs is no problem.  On my local my dev box I can insert around 14K docs per second.  Of course the speed will depend greatly on the size of the documents and the speed of the machine.  

Lucene manages the segments well and will merge them periodically.  The result will be less segments but bigger segments.  You can make Lucene's life easier and your indexing faster by not calling `Flush`, `Commit` or `MaybeRefreshBlocking` until after you have inserted the set of documents you desire.  (These commands force buffered documents to be written out in a new segment).  But even if you call all these methods after each time you add a document to the index Lucene will still manage the segments well by doing merging as needed. It will just be much slower (maybe like 20 docs per second).
