### ISSUE TITLE
Exception with ICharTermAttribute when adding docs to the index

### ISSUE THREAD

**Issue by mjbedford2017** [apache/lucenenet#510]
Hello, 

I have been having an issue lately. I don't remember seeing this before when using Lucene.Net in my projects. I am basically following the quick start on your website [Lucene.Net](https://lucenenet.apache.org/). In my case, I am using a BaseRamStore and I am using the search engine to find names of people. So, I create a bunch of Documents that have the name defined in them as a string field. I then iterate them and call `writer.AddDocument` to add each document to the search engine. 

However, I am now getting an exception when I AddDocument that states it cannot find the ICharTermAttribute. 

I wish I had more information but it seems that since this is happening in AddDocument and I added Lucene.Net as a nuget package, I cannot step in to the code/library. Any ideas to throw on the wall?

EDIT: Here is a stack trace I was able to get for the exception. I was able to catch it.

```
   at Lucene.Net.Util.AttributeSource.GetAttribute[T]()
   at Lucene.Net.Index.TermsHashPerField.Start(IIndexableField f)
   at Lucene.Net.Index.DocInverterPerField.ProcessFields(IIndexableField[] fields, Int32 count)
   at Lucene.Net.Index.DocFieldProcessor.ProcessDocument(Builder fieldInfos)
   at Lucene.Net.Index.DocumentsWriterPerThread.UpdateDocument(IEnumerable`1 doc, Analyzer analyzer, Term delTerm)
   at Lucene.Net.Index.DocumentsWriter.UpdateDocument(IEnumerable`1 doc, Analyzer analyzer, Term delTerm)
   at Lucene.Net.Index.IndexWriter.UpdateDocument(Term term, IEnumerable`1 doc, Analyzer analyzer)
   at Lucene.Net.Index.IndexWriter.AddDocument(IEnumerable`1 doc, Analyzer analyzer)
   at Lucene.Net.Index.IndexWriter.AddDocument(IEnumerable`1 doc)
   at OdenIndustries.RecipientSearch.LuceneWrapper.BaseStore.AddItemToIndex(ADocument doc, IndexWriter writer) in C:\OdenRepo\LibraryComponents\OdenIndustries.RecipientSearchV2.NetStandard\LuceneWrapper\BaseStore.cs:line 27
```

And here is the line that catches this exception:

        public void AddUpdatePersonToIndex(RecipientSearchItem recipient)
        {
            store.AddUpdateItemsToIndex(new List<RecipientDocument> { (RecipientDocument)recipient });
        }

The store variable above is a BaseStore

      private BaseStore store;

And that RecipientDocument is my class, which inherits from ADocument to create my fields that I search on. Here it is:

    public class RecipientDocument : ADocument
    {
        private string lastName;
        private string firstName;
        private string fullName;

        [SearchField]
        public string LastName
        {
            get { return lastName; }
            set
            {
                lastName = value;
                if (lastName == null)
                    lastName = "";
                AddParameterToDocumentNoStoreParameter("LastName", lastName);
            }
        }

        [SearchField]
        public string FirstName
        {
            get { return firstName; }
            set
            {
                firstName = value;
                if (firstName == null)
                    firstName = "";
                AddParameterToDocumentNoStoreParameter("FirstName", firstName);
            }
        }

        [SearchField]
        public string FullName
        {
            get { return fullName; }
            set
            {
                fullName = value;
                if (fullName == null)
                    fullName = "";
                AddParameterToDocumentNoStoreParameter("FullName", fullName);
            }
        }

        public static explicit operator RecipientDocument(RecipientSearchItem person)
        {
            return new RecipientDocument()
            {
                LastName = person.LastName,
                FirstName = person.FirstName,
                FullName = person.FullName,
                Id = person.Id
            };
        }
    }

And to summarize the issue, if I create some of the documents above, with different names and I try to add them to the index, this is where I get the exception caught above which ultimately has an issue finding the ICharTermAttribute

Thanks!!

Mike

**Comment by NightOwl888** [comment]
Thanks for the report.

It looks like you are using Lucene.NET 3.0.3. All of the examples from our home page are for Lucene.NET 4.8.0-beta. 

In Lucene 3.0.3, the `ICharTermAttribute` was named `ITermAttribute` instead, and that is [the type it is trying to load in TermsHashPerField](https://github.com/apache/lucenenet/blob/3.0.3/src/core/Index/TermsHashPerField.cs#L290).

The API documentation for Lucene.NET 3.0.3 can be found here: https://lucenenet.apache.org/docs.html.
