### ISSUE TITLE
Docs: Windows 2016 Deprecation on Azure DevOps/GitHub Actions - March 15, 2022 Deadline

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#601]
Microsoft will be removing the `vs2017-win2016` image on March 15, 2022, so our docs automation that use this (whether on Azure DevOps or on GitHub) will quit functioning.

https://github.com/actions/virtual-environments/issues/4312
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows

### Options

1. Upgrade DocFx to use a later version of Visual Studio
2. Create our own build agent in Azure to build the docs (note we have been provided with Azure credits complements of Microsoft, but we don't yet have an official Azure account to put them in)

According to https://github.com/dotnet/docfx/issues/5553#issuecomment-591275853, VS2019 is now supported by DocFx 2.49, and we are currently on 2.58. So, we need to run some tests with newer images to determine whether the path is already clear to upgrade to a newer image for the docs build.

@Shazwazza - Do you know of any specific reason why upgrading would not be possible?

**Comment by Shazwazza** [comment]
Should be fine :) I saw your PR https://github.com/apache/lucenenet/pull/603 i'll have a look later today hopefully
