### ISSUE TITLE
Int search/filter resulting in no results.

### ISSUE THREAD

**Issue by diegolaz79** [apache/lucenenet#629]
Hello, I'm doing a search first by text and then a second search with same text by adding some number filters:
First search, results in a lot of results
{+(username:*carlos* address:*carlos* country:*carlos* description:*carlos* notes:*carlos* ) }

I then add a filter of userid = 1. 

Tried first like a TextField:
```
 Query q = new TermQuery(new Term("userid", userid.Trim().ToLower()));
 booleanQuery.Add(q, Occur.MUST);
resulting in
{+(username:*carlos* address:*carlos* country:*carlos* description:*carlos* notes:*carlos* ) +usrid:1}
```

Then like a number range
```
int usrID = int.Parse(userid);
Query q = NumericRangeQuery.NewInt32Range("userid", usrID, usrID, true, true);
booleanQuery.Add(q, Occur.MUST);   
resuing in
{+(username:*carlos* address:*carlos* country:*carlos* description:*carlos* notes:*carlos* ) +usrid:[1 TO 1]}
```

While indexing, these are the two approaches I took:
```
new Int32Field("userid", (int)(userID != null ? userID : 0), Field.Store.YES),
new TextField("userid",(userID != null ? userID.ToString() : ""), Field.Store.YES),
```

And for analyer, I'm using 
```

IDictionary<string, Analyzer> customAnalyzerPerField = new Dictionary<string, Analyzer>();
customAnalyzerPerField ["userid"] = new StandardAnalyzer(LuceneVersion.LUCENE_48);
// also tried customAnalyzerPerField ["userid"] = new WhitespaceAnalyzer(LuceneVersion.LUCENE_48);
```

Any ideas on why its filtering to empty? (I checked DB and for that field there are a few rows that should match).

**Comment by diegolaz79** [comment]
Checking while creating the index, and its saving for example this as a field of index document:

`{stored,indexed,tokenized,omitNorms,indexOptions=DOCS_ONLY,numericType=INT32,numericPrecisionStep=4<userid:1>}`

**Comment by NightOwl888** [comment]
Are you seeing a difference in NumericRangeQuery behavior between 4.8.0-beta00016 and prior versions? We did make a few changes to it to avoid boxing. https://github.com/apache/lucenenet/pull/570/commits/2cae3c28001ff350a516635f33670581e8c58b85

I haven't spotted a problem with the query, but I noticed that there are different modes demonstrated in [the NumericRangeQuery tests](https://github.com/apache/lucenenet/blob/Lucene.Net_4_8_0_beta00016/src/Lucene.Net.Tests/Search/TestNumericRangeQuery32.cs#L167-L194) that you might want to experiment with.

**Comment by diegolaz79** [comment]
Thanks both! I will check those links and test and use StackOverFlow in the future. 
If that doesn't work I will provide a small sample code
Yes, the usrid was a typo here in the question.
Thanks!!

**Comment by yohsii** [comment]
i've written a custom query parser for my cms
https://github.com/yohsii/puck-core/blob/master/core/PuckLucene/PuckQueryParser.cs

starting line 89 should handle your integer search

**Comment by diegolaz79** [comment]
> i've written a custom query parser for my cms https://github.com/yohsii/puck-core/blob/master/core/PuckLucene/PuckQueryParser.cs
> 
> starting line 89 should handle your integer search

worked like a charm

**Comment by NightOwl888** [comment]
@diegolaz79 @yohsii

Do note that some cultures use alternate characters for the negative sign. So, for `int. Parse()` and `long.Parse()`, passing `CultureInfo.InvariantCulture`  may be required if the input may contain negative numbers that don't match the culture of the current thread.

**Comment by rclabo** [comment]
@NightOwl888  

>Do note that some cultures use alternate characters for the negative sign. So, for int.Parse() and long.Parse(), passing CultureInfo.InvariantCulture may be required if the input may contain negative numbers that don't match the culture of the current thread.

Wouldn't you have to pass the `CultureInfo` for that culture in order for the `Parse()` method to correctly know how the negative number is represented?  Seems like `CultureInfo.InvariantCulture` wouldn't contain that info?
