### ISSUE TITLE
Question: See "Tokens" Frequency?

### ISSUE THREAD

**Issue by dgerding** [apache/lucenenet#637]
Hi,
Assuming I've got an index of a lot of documents, is there a way to "get" a list of the tokens (even just "whitespace separated" strings /  "words" ) and the frequency? Put another way, is there a way to configure a Lucene search store to generate a comprehensive word frequency list from the corpus? 

(Not sure I'm saying that right. Thanks for any leads or insights.)

**Comment by NightOwl888** [comment]
Sorry for the delay. This isn't the right place to be asking user questions for Lucene.NET. We have a [user mailing list](https://lucenenet.apache.org/contributing/index.html#ask-a-question) for that, but you are probably more likely to get an answer on [StackOverflow](https://stackoverflow.com/questions/tagged/lucene.net) or by asking on the [Lucene Java-user mailing list](https://lucene.apache.org/core/discussion.html). Questions like this will have the same answer in both .NET and Java, so if you ask on StackOverflow be sure to add both the `lucene` and `lucene.net` tags.
