### ISSUE TITLE
VectorHighlight Documentation

### ISSUE THREAD

**Issue by KuzonCode** [apache/lucenenet#643]
I have been reading through the documentation on [Vector Highlighting](https://lucenenet.apache.org/docs/4.8.0-beta00016/api/highlighter/Lucene.Net.Search.VectorHighlight.html). I am struggling to work out how to implement it in my project. I want to be able to hit highlight the whole document, but can't quite work out the Vector Highlighting or how to expand the standard highlighter to return the whole document.

Is there somewhere I could find more documentation on how fully implement a Vector Highlighter? There is no full example in the documentation and would really appreciate it if someone could point me to one. 

Also is there a way I can import a full html document with analyzers? I would like to be able to apply highlighting to a full HTML document.

**Comment by rclabo** [comment]
Sorry we have all been swamped and were unable to provide any feedback or suggestions.  Were you able to get the Vector Highlighting working the way you wanted?  Are you able to contribute back any documentation or samples for doing it?

**Comment by KuzonCode** [comment]
@rclabo No worries at all! Totally understand. Unfortunately, no I have not had any luck with implementing it current. It's still something I would love to get going, but just have not been able to nut it out yet.

**Comment by NightOwl888** [comment]
@KuzonCode - There are a few places you might find helpful to look. 

A little Googling turned up this blog post: http://makble.com/how-to-do-lucene-search-highlight-example.  https://blog.mikemccandless.com/ is also a good place to find details about Lucene.

It may also help to check out the vector highlighter tests in the [Lucene.Net.Tests.Highlighter](https://github.com/apache/lucenenet/tree/b5ea527c5bd125dd1db34d8b914e1a5d72e08ffa/src/Lucene.Net.Tests.Highlighter) folder.

> **NOTE:** When viewing these in Visual Studio or trying to find the classes under test on NuGet, be aware that the actual classes are split between the `Lucene.Net.Tests.Highlighter` project and the `Lucene.Net.Tests.ICU` project (the latter can be found below the dotnet folder). The reason for this is that .NET has no equivalent to the `BreakIterator` class, so we add a dependency on ICU4N in the classes that require it. Generally `BreakIterator` is only required when you are dealing with a script that doesn't delineate tokens with spaces (such as Thai) or when it is right-to-left (such as Arabic).

**Comment by KuzonCode** [comment]
@NightOwl888 Appreciate it! I think the first example was predominantly the simple highlighters. But that test suite should be good. Will see what I can build with the example in there. Appreciate your time

**Comment by NightOwl888** [comment]
Closing as this appears to be resolved.
