### ISSUE TITLE
Infinite loop in HttpClientBase?

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#653]
I have a reported Issue on SonarCloud that marks a infinite loop: https://sonarcloud.io/project/issues?issues=AYPAuQh1hbfJOGLOob-o&open=AYPAuQh1hbfJOGLOob-o&id=nikcio_lucenenet

From what I can gather I too see this is a infinite loop but I don't know if I'm missing something:

https://github.com/apache/lucenenet/blob/edc85aff62c5bc52d6698ff538ec29d59207f5a6/src/Lucene.Net.Replicator/Http/HttpClientBase.cs#L466

Looking at the code around it I would think it should be this instead:

```csharp
public override void Write(byte[] buffer, int offset, int count) => input.Write(buffer, offset, count);
``` 

But I don't know enough about what's happening in this part of the code yet so I would like some help assessing it😅

**Comment by NightOwl888** [comment]
Yes, I agree this is the appropriate fix.
