### ISSUE TITLE
Review all Flags enums to ensure they use valid options

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#658]
We could use a review to ensure more issues such as #657 do not exist in the project, and patches submitted if there are any remaining. This was caught by SonarQube in #648 under the heading `Non-flags enums should not be marked with "FlagsAttribute"`.

https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=nikcio_lucenenet&open=AYPAuPk6hbfJOGLOobJj

**Comment by nikcio** [comment]
Issues relating to this issue can be seen under: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS4070&id=nikcio_lucenenet
