### ISSUE TITLE
All DefaultSetHolder classes (in Analyzers) should be marked static

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#659]
This was picked up by SonarCloud

https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=nikcio_lucenenet&open=AYPAuPhThbfJOGLOobIl

While these were marked `static` in Lucene, the `static` keyword has a different meaning in Java (basically, it just means "nested" and you can still instantiate them). However, since there are no members that are non-static, adding this keyword in .NET is appropriate and recommended.

There are a few dozen of these classes in analyzers which should all be consistently named (some of which may not be in `Lucene.Net,Analysis.Common`), so this is a straightforward fix.

> **NOTE:** There are some other classes that have inconsistent names but have a similar purpose. But most of them are suffixed with `Holder`.

**Comment by nikcio** [comment]
Similar issues can be seen under: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1118&id=nikcio_lucenenet
