### ISSUE TITLE
Lucene.Net.Analysis.Ja.Util.CSVUtil.QuoteEscape is not escaping quotes

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#660]
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=nikcio_lucenenet&open=AYPAuQAohbfJOGLOobtL

We should be overwriting the value of `return` here, but we are not.

This needs to be analyzed further by comparing against [Lucene 4.8.1](https://github.com/apache/lucene/tree/releases/lucene-solr/4.8.1):

1. If this is a bug in the translation from Java to .NET, we should simply fix it.
2. If this is a bug that still exists in the current version of Lucene, we should both fix it and report it to them.
3. If this is a bug that existed in 4.8.1 but was fixed since, we need to track down the [JIRA](https://issues.apache.org/jira/projects/LUCENE/issues)/[GitHub](https://github.com/apache/lucene/issues) issue number and leave a comment indicating the issue number of the patch that has been applied. The entire patch should be analyzed and we should bring over all changes from the patch. We should also look up and include the Lucene version number(s) it was released in so we know when to remove the comment.

**Comment by nikcio** [comment]
Link to issue isolated from other issues: https://sonarcloud.io/project/issues?issues=AYPAuQAohbfJOGLOobtL&open=AYPAuQAohbfJOGLOobtL&id=nikcio_lucenenet
