### ISSUE TITLE
Review for CA1822: Mark members as static

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#663]
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=nikcio_lucenenet&open=AYPAuPfOhbfJOGLOobHM
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822

Members that do not access instance data or call instance methods can be marked static. This may diverge from the Java implementation, so we should mark these members with the comment `// LUCENENET: CA1822: Mark members as static`.

A check should be made against the Lucene source code first before applying this change. If there is no `final` modifier on a method in Java...

```java
public void DoSomething() {
   // impl
}
```

...it means it should be declared `virtual` in .NET (unless the class is sealed).

```c#
public virtual void DoSomething()
{
   // impl
}
```

In this case, we cannot declare the method/property `static` and instead add the missing `virtual` modifier.

> `**NOTE:** The entire codebase has been manually reviewed already to catch the virtual/non-virtual declarations, however, since this review was manual, there may have been some that were missed.

**Comment by nikcio** [comment]
Similar issues can be found here: https://sonarcloud.io/project/issues?resolved=false&rules=external_roslyn%3ACA1822&severities=INFO&id=nikcio_lucenenet

**Comment by nikcio** [comment]
I'll look into this one

**Comment by NightOwl888** [comment]
Great work!
