### ISSUE TITLE
Remove this call from a constructor to the overridable 'xxx' method/property

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#670]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1699&id=apache_lucenenet

This is a difference in initialization order between Java and .NET. In Java it is safe to make a call to a virtual member from a constructor, but in .NET it is not. Same issue in https://github.com/apache/lucenenet/issues/408. I still haven't found a good solution to this, but it would be nice to have a list of all of the places where it is a problem so we can consider what solution(s) will work.

**Comment by laimis** [comment]
All the issues that were reported by this rule have been addressed. Thank you for setting this up and reporting it!

The fixing PRs have been linked to the issue and can be reviewed to see what was done. In some cases we were able to ignore the warning, in other cases we created private methods that can be called from the constructor, as well as the virtual methods where it was safe to do so. In publicly exposed classes that needed the functionality we introduced factory classes that are passed to the constructor and can be extended to introduce custom behavior.
