### ISSUE TITLE
Remove this empty statement

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#671]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1116&id=nikcio_lucenenet

When these are extra `;` characters, they are most likely just typos. For [labeled continue statements](https://www.programiz.com/java-programming/continue-statement#labeled-continue), we inconsistently use `;` and `{ }`, both which trigger this warning. For those, we should probably use the latter approach and add an inline comment `/* LUCENENET: intentionally blank */` between the curly brackets.

**Comment by NightOwl888** [comment]
Fixed in #730
