### ISSUE TITLE
Either remove or fill this block of code

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#672]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS108&id=apache_lucenenet

The comment associated with the line can be moved inside of the curly brackets to make it non-empty. If there is no comment, just add `// LUCENNET: intentionally empty`. Exception: empty finally blocks - we can remove the entire try/finally out of the methods in `JavascriptLexer`. Leave a comment `// LUCENENET specific - removed unnecessary try/finally block` in each method where they are removed.

**Comment by NightOwl888** [comment]
Hmm...the SonarCloud link is not returning any results.

**Comment by nikcio** [comment]
Should be fixed now
