### ISSUE TITLE
Correct this '&' to '&&'

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#673]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS2178&id=nikcio_lucenenet

Check the [Lucene 4.8.1 source](https://github.com/apache/lucene/tree/releases/lucene-solr/4.8.1) on this to see whether this is a translation bug or a bug carried over from Lucene, and report appropriately.

1. If this is a bug in the translation from Java to .NET, we should simply fix it.
2. If this is a bug that still exists in the current version of Lucene, we should both fix it and report it to them.
3. If this is a bug that existed in 4.8.1 but was fixed since, we need to track down the [JIRA](https://issues.apache.org/jira/projects/LUCENE/issues)/[GitHub](https://github.com/apache/lucene/issues) issue number and leave a comment indicating the issue number of the patch that has been applied. The entire patch should be analyzed and we should bring over all changes from the patch. We should also look up and include the Lucene version number(s) it was released in so we know when to remove the comment.

**Comment by nikcio** [comment]
I'll look into this one 😄

**Comment by nikcio** [comment]
I've tracked down this commit in the Lucene repository: https://github.com/apache/lucene/commit/55594bad9b07af90de4ab2a2fb0bac8e8c2b0b3c#diff-ccf964ce5c3d619df7e73dd7c1467cd88265240d7bdc1c35c27bfc02d669d6c8

It seems the file was deleted and I haven't been able to find it in versions 5.0.0 and above. I can see that the single '&' was still in the 4.10.4 version: https://github.com/apache/lucene/blob/69175ad4fe8d224ad6a348d05f686105999a92e8/lucene/analysis/common/src/java/org/apache/lucene/analysis/nl/DutchStemmer.java#L193

So it might just be to fix the issue.

**Comment by NightOwl888** [comment]
Well, being that it doesn't make any sense to use a bitwise `&` operator here, it makes sense just to change it.

Looks like the current version is using the snowball stemmer: https://github.com/apache/lucene/blob/cc342ea7407c729a743123d8f7957aff6c6f9792/lucene/analysis/common/src/java/org/apache/lucene/analysis/nl/DutchAnalyzer.java. Snowball is poached from: https://github.com/weavejester/snowball-stemmer. The Snowball [DutchStemmer](https://github.com/apache/lucenenet/blob/089a439d82e95708d55f39a64206cccba39cf5da/src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/DutchStemmer.cs) exists in 4.8.0, but apparently, they hadn't gotten around to upgrading it yet.
