### ISSUE TITLE
Rename 'xxx' which hides the field with the same name

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#678]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS1117&id=apache_lucenenet

We can fix this for the static readonly fields. In regular instance methods, we should leave it alone unless it diverges from Lucene.

**Comment by paulirwin** [comment]
I reviewed _all 206_ of these issues, and of those, only 15 were ones we should fix. The remaining were the same as in Lucene, so we should not fix it as it is too risky, as noted in this original issue text. I've marked the 191 items we won't fix as "Accepted" with a reason of "Matches Lucene." After discussion with @NightOwl888, we feel this is preferable to littering our code with suppressions. The remaining I'll get a PR for.
