### ISSUE TITLE
Replace the control character at position 2 by its escape sequence '\u3000'.

### ISSUE THREAD

**Issue by nikcio** [apache/lucenenet#680]
Mentioned in #648 

Issues found: https://sonarcloud.io/project/issues?resolved=false&rules=csharpsquid%3AS2479&id=nikcio_lucenenet

This should be marked with a `// LUCENENET specific - changed from invisible whitespace character to '\u3000' for readability`.

**Comment by NightOwl888** [comment]
There appears to be a bug in the SonarCloud analyzer report. The `'\u3000'` character is at position 1, not position 2.

```
?(int)" 　\t\r\n"[0]
32
?(int)" 　\t\r\n"[1]
12288
?(int)" 　\t\r\n"[2]
9
?(int)" 　\t\r\n"[3]
13
?(int)" 　\t\r\n"[4]
10
?(int)'\u3000'
12288
```

**Comment by nikcio** [comment]
@NightOwl888 I think that it starts counting at 1 instead of 0 and that's why it says 2.
