### ISSUE TITLE
All methods, fields, and properties should be marked `private` instead of `internal` in all anonymous classes

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#715]
Anonymous classes are suffixed `AnonymousClass`.

In Java, [anonymous classes](https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html) are declared inline, so there is no other code that can interact with them.

However, many of these classes (such as [this example](https://github.com/apache/lucenenet/blob/b6cf28b78c85f33e66d89abe399c4523dd41dc80/src/Lucene.Net.Misc/Index/Sorter/BlockJoinComparatorSource.cs#L102)) have methods, fields, and properties that are marked `internal`. `internal` was chosen because in Lucene it is common to leave off an accessibility modifier.

- In Java, if there is no accessibility modifier, the accessibility defaults to `package-private`, which is similar to `internal`.
- In .NET, if there is no accessibility modifier, the accessibility defaults to `private`.

However, in an anonymous class, `package-private` accessibility is not sensible. It has the same effect as declaring the member `private`.

Therefore, all methods, fields, and properties of anonymous classes can be changed to `private` and we should leave a comment indicating that the change was made.

```// LUCENENET: changed accessibility from internal to private```

There may be exceptions in cases where members were added to make testing easier, so those may need to remain `internal`. A compile can quickly identify members that should be left alone.

**Comment by rishav-karanjit** [comment]
Hello @NightOwl888, can I work on this issue?

Is this issue all about changing internal to private?

**Comment by NightOwl888** [comment]
Sure. This is about accessibility of the members of the anonymous classes to make the members unavailable to the calling code (except for the member variables that are initialized in the constructor). It is less of a concern for members that are part of an interface or base class to make the members private (and in the latter case they must be the same accessibility as the base class), but all of the fields should definitely be hidden from the outside world.

We have already done some improvements to the naming conventions of the anonymous classes in #426 and #666 so they all end in the suffix `AnonymousClass`, making them easier to find. #666 also has marked them all `private` and `sealed`.
