### ISSUE TITLE
Frequent Commit operations consume a lot of CPU

### ISSUE THREAD

**Issue by zhangbaodan** [apache/lucenenet#720]
I plan to use lucene to build a PC file search system, In order to search the newly generated files in time, I have to do the following operations:

1. Every few seconds, the system obtains file changes from the USN log and uses IndexWriter to Commit the new file index to the local disk.

2. On each search, IndexReader will be recreated from disk to ensure that IndexReader gets the latest data.

But this has two bad effects:

1. Commit operations are too frequent, resulting in high CPU consumption.

2. During each search, it takes about 80ms to recreate IndexReader from the disk index, resulting in high search latency.

What can I do to reduce the CPU consumption by reducing the frequency of Commit operations while keeping the search real-time?

**Comment by nikcio** [comment]
@zhangbaodan I think this might help you with finding a solution: https://stackoverflow.com/questions/32269632/writing-to-lucene-index-one-document-at-a-time-slows-down-over-time

**Comment by rclabo** [comment]
@nikcio is pointing you in the right direction. The key aspect from that SO answer is this:

>Use a [SearcherManager](https://lucene.apache.org/core/5_0_0/core/org/apache/lucene/search/SearcherManager.html) for searching and invoke [maybeRefresh()](https://lucene.apache.org/core/5_0_0/core/org/apache/lucene/search/ReferenceManager.html#maybeRefresh()) periodically to see updated documents within a reasonable time frame

And that assumes your `IndexReader` was created from `IndexWrite.GetReader()` rather then created independently.

With those tips you should see much better performance.

**Comment by zhangbaodan** [comment]
@nikcio @rclabo   Thank you very much for your timely reply, which really helped me a lot. By adopting your suggestions, my cpu consumption was reduced from 4% to less than 0.1%. This is really a huge improvement. Here's my solution:

1. Every few seconds, retrieve file changes from the USN log and write them to IndexWriter via UpdateDocument, but do not immediately commit them to local disk.

2. Create an IndexReader from the IndexWriter during each search. This ensures that the IndexReader can see the new data in the IndexWriter and the data on the disk. Here is the corresponding code :https://gist.github.com/mocobeta/4640263

3. The timing of IndexWriter commits is important. Here I recommend that you commit every 10 minutes, and at the same time, you should record the location of the current USN log read. The next time the program is started, the USN will continue reading from the recorded location. This ensures that all changes read in the USN log are recorded in the index file.

**Comment by rclabo** [comment]
@zhangbaodan 

>Create an IndexReader from the IndexWriter during each search. This ensures that the IndexReader can see the new data in the IndexWriter and the data on the disk. Here is the corresponding code

You don't need to recreate `IndexReader` from the `IndexWriter` during each search.  Use the same `IndexReader`  over and over that you initially obtained from `IndexWrite.GetReader()` and then call `searcherManager.MaybeRefresh()` before each search is performed. That's all that's needed to ensure the `IndexReader` can see the new data that the `IndexWriter` has written.  

`searcherManager.MaybeRefresh()`  is about "Visibility" and commit is about "Durability".  So when you call `searcherManager.MaybeRefresh()` the `IndexReader` will see the data even if you haven't called commit yet.   `searcherManager.MaybeRefresh()`  causes you to see the data, commit causes the data to be written to disk and committed to the index. They each work totally independently of each other.

**Comment by zhangbaodan** [comment]
@rclabo  You are right, I should have each search, first call searcherManager. MaybeRefresh (). However, in the PC search scenario, at least 10+ files are generated every second, and the user's search operation is very low frequency. So every time you search, MaybeRefresh must be true. So I took the lazy step of just getting IndexReader from IndexWriter, which took almost 0ms

In a word, I really like your solution, which helped me a lot.
