### ISSUE TITLE
ICUTokenizer discrepancies

### ISSUE THREAD

**Issue by krinsang** [apache/lucenenet#732]
I've noticed that the ICUTokenizer for Thai will not generate the same tokens as the Java variant. I've tested the latest beta version of the .NET project against the Apache  Lucene v4.8.0. Even making sure that either implementations use the same `.brk` files did not yield consistent results.

**Comment by NightOwl888** [comment]
I just re-read your report and realized you were referring to `ICUTokenizer` rather than the `ThaiTokenizer`.

The reason why the behavior differs from Lucene 4.8.0, is because we ported the [`ICUTokenizer` from Lucene 8.6.1](https://github.com/apache/lucenenet/blob/ebcd9ea985001580cdd9f6f90801c605fe19a250/src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ICUTokenizer.cs#L1). Can you confirm that the behavior is the same as Lucene 8.6.1?

**Comment by krinsang** [comment]
Yes, I just compared version 8.6.1 to to 4.8.0-beta00014 and the two tokenizers yield different results.

**Comment by NightOwl888** [comment]
Could you put together a test or console app we can run in both environments so we can take a look?

**Comment by krinsang** [comment]
https://github.com/krinsang/lucenenet/tree/bug/icutokenizer
please use my forked branch as a reference.

**Comment by krinsang** [comment]
Yes, you're correct about the `StopFilter`. The `StopFilter` is reflected isometrically between both .NET and Java. I've reviewed the results again without the `StopFilter` but I'm still running into issues. A specific example:
.NET:
```
keyword: กล่องใส่รองเท้า
tokenized components: "กลอง", "ใส", "รอง", "เทา"
```
Java:
```
keyword: กล่องใส่รองเท้า
tokenized components: "กล่อง", "ใส่", "รองเท้า"
```

It seems as if the ICUTokenizer in .NET seems to tokenize the keywords into small units which is not observed in Java.

**Comment by krinsang** [comment]
I am not using the `ICUNormalizer2Filter` anywhere in my code, and I'm not seeing that it's being referenced in the `ICUTokenizer` class.

**Comment by NightOwl888** [comment]
Could you post the code for how you are constructing the analyzer including how you are setting up the `StopFilter`? Something in your token stream is filtering out diacratics. We are most likely looking at some sort of a gap between how .NET and Java handle localization or normalization, but this doesn't appear to be directly related to `ICUTokenizer` or `CharArraySet`.

**Comment by NightOwl888** [comment]
Oh, and be sure to include the culture name (i.e. `en-US`) of the thread you are running this on.

**Comment by krinsang** [comment]
[Analyzers.zip](https://github.com/apache/lucenenet/files/9930442/Analyzers.zip)

**Comment by NightOwl888** [comment]
Thanks. Still no luck getting the results you are seeing. I tried both `net5.0` and `net48` and even checked out the beta 14 tag to see if there was a difference, but no dice.

One thing of note: Thai has no concept of uppercase/lowercase, so if you are not analyzing text with other scripts in it that can be omitted. It will also improve performance.

So, for a repro we need to know more about your environment:

1. Which runtime are you using? .NET Framework, .NET Core, Unity, Xamarin, Mono, etc? Which specific version?
2. Which OS are you trying this on? Which specific version?
3. What is the default culture set to on the OS?
4. What is the culture of the current thread when you run this?

It would also be helpful if you could setup a basic test that fails in an environment such as GitHub Actions or Azure DevOps so we can rule out anything with your specific environment.

**Comment by krinsang** [comment]
I've deduced the problem down to a difference in the way that the normalizer for Java and .NET were handling accented characters. While .NET's `System.String.Normalize` was able to detect and decompose the accented characters, the `Normalizer` class in `java.text` did not apply the same modifications to the original query.
