### ISSUE TITLE
Does lucene.net support near-real-time segment replication 

### ISSUE THREAD

**Issue by yashhema** [apache/lucenenet#758]
Hello,
Does lucene .net supports near real time segment replication

regards

**Comment by rclabo** [comment]
Lucene.NET does provide hooks for implementing index replication.  I was going to point you to [issue 401](https://github.com/apache/lucenenet/issues/401#issuecomment-759258652) to learn more but I see you participated in that discussion.  

While I haven't done it personally, I would think that the `Replicator.Publish` approach documented in issue 401 would be near real time.  Is that not the case?  Are you seeing or experiencing something different?

**Comment by NightOwl888** [comment]
The GitHub issues is not a general Q & A forum, we use it to track the tasks that we need to do to complete the port and then move on to upgrading it to the latest version of Lucene. Please direct any general usability questions to [StackOverflow](https://stackoverflow.com/questions/tagged/lucene.net) (be sure to include the `lucene` tag if it is not specifically about .NET) or the [Lucene.NET user mailing list](https://lucenenet.apache.org/contributing/mailing-lists.html#users-user).
