### ISSUE TITLE
Incorrect Handling of Some German Special Characters in FoldToASCII

### ISSUE THREAD

**Issue by ab-tools** [apache/lucenenet#770]
Following German special characters should be converted to 2 characters instead of just 1 in this function:
https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/ASCIIFoldingFilter.cs#L166

Ä => AE (instead of just A)
Ö => OE (instead of just O)
Ü => UE (instead of just U)
ä => ae (instead of just a)
ö => oe (instead of just o)
ü => ue (instead of just u)

**Comment by laimis** [comment]
We follow Java version for this logic and it looks like they convert it to single letters:

https://github.com/apache/lucene/blob/8ac26737913d0c1555019e93bc6bf7db1ab9047e/lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.java

**Comment by laimis** [comment]
Sounds good, I will go ahead and close this ticket then, and we can follow the java version lead with what they decide.

**Comment by NightOwl888** [comment]
I'd suggest trying the [ICUFoldingFilter](https://lucenenet.apache.org/docs/4.8.0-beta00016/api/icu/Lucene.Net.Analysis.Icu.ICUFoldingFilter.html). Alternatively, if you just need a straight case fold the [ICUNormalizer2Filter has a constructor with that option](https://lucenenet.apache.org/docs/4.8.0-beta00016/api/icu/Lucene.Net.Analysis.Icu.ICUNormalizer2CharFilter.html#Lucene_Net_Analysis_Icu_ICUNormalizer2CharFilter__ctor_System_IO_TextReader_), which is the strict interpretation of Unicode.
