### ISSUE TITLE
Limit memory usage - Setting RAMBufferSizeMB and RAMPerThreadHardLimitMB in IndexWriterConfig has no effect

### ISSUE THREAD

**Issue by PeterOeClausen** [apache/lucenenet#784]
Note that this question is also posted on StackOverflow: https://stackoverflow.com/questions/74850659/apache-lucenenet-unable-to-limit-memory-usage-rambuffersizemb-ramperthreadhar

I'm running the latest Lucene .NET versions:
Lucene.Net 4.8.0-beta00016
Lucene.Net.Analysis.Common 4.8.0-beta00016

I'm doing the following:
```cs
            using var analyzer = new KeywordAnalyzer();
            using var directory = FSDirectory.Open(IndexPath);
            var config = new IndexWriterConfig(LuceneVersion, analyzer)
            {
                OpenMode = OpenMode.CREATE, // Use OpenMode.CREATE to overwrite, or OpenMode.APPEND to just open
                RAMPerThreadHardLimitMB = 100,
                RAMBufferSizeMB = 100,
            };
            using var writer = new IndexWriter(directory, config);
            
            // Write index to disk
            writer.AddDocuments(productDocuments);
            writer.AddDocuments(productCategoryDocuments);
            writer.AddDocuments(productTypeDocuments);
            writer.AddDocuments(productLineDocuments);
            writer.Commit();
```

As soon as writer.AddDocuments() is called, the memory consumption grows a lot.
You can see the sudden increase in the Diagnostic Tool in visual studio: 
![image](https://user-images.githubusercontent.com/6975621/208420492-6c9d779d-1991-4a0c-9819-eaefea00919b.png)

Running it multiple times keeps increasing the memory usage up to 3GB, at which point it doesn't grow any longer. And these 3GB are never released again. The program doesn't crash, and it stops acquiring memory.

I want to limit how much memory Lucene can use, but using `RAMBufferSizeMB` and `RAMPerThreadHardLimitMB` seems to have no effect at all.

I tried flushing as well, which had no effect, and I tried calling Dispose() which also had no effect.

I've also tried setting MaxBufferedDocs to 1000, still no limit to RAM usage.

Have I missed something in the documentation? Is there a way to limit RAM usage of the Lucene .NET IndexWriter?

**Comment by NightOwl888** [comment]
`RAMBufferSizeMB` is for *increasing* the amount of allocations to improve performance when indexing a large number documents, as pointed out in [the demo](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Demo/IndexFiles.cs#L103-L107).

`RAMPerThreadHardLimitMB` controls how frequently a background flush will occur.

Both of these settings are fully implemented and a flush will cause Lucene.NET to release the references. But at the end of the day, the garbage collector is in charge after the references have been released by Lucene.NET.

See [Fundamentals of garbage collection](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals)

While it is generally discouraged to run a garbage collection yourself, .NET does provide a [GC.Collect](https://learn.microsoft.com/en-us/dotnet/api/system.gc.collect?view=net-7.0) method to explicitly force a garbage collection. If you run the garbage collector and the amount of RAM doesn't decrease, then perhaps we have an issue.

However, do keep in mind that the debugger in Visual Studio adds a lot of memory overhead that won't be seen in production.

> **NOTE**: If this is a .NET Framework app or your app is using the .NET Standard 2.0 target of Lucene.NET, there may be another reason for this. The `ConditionalWeakTable<TKey, TValue>` is missing an enumerator prior to .NET Standard 2.1, which is required in several places by Lucene. We [worked around the issue using weak events](https://github.com/apache/lucenenet/pull/613), but at the end of the day `WeakReference` holds onto references longer than `ConditionalWeakTable<TKey, TValue>`. In these cases, not even calling `GC.Collect` can recover the memory, the only option is to wait for the memory to be released.
>
> There is another option using [WPF WeakEventManager](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/weak-event-patterns?view=netdesktop-6.0) that uses `ConditionalWeakTable<TKey, TValue>` plus some native code to resolve the issue, but since there is no support for this on .NET Standard 2.0, we didn't explore this option any further. But since we are now considering dropping support for .NET Standard 2.0 anyway, perhaps it is worth another look.

**Comment by PeterOeClausen** [comment]
Thanks for the response.
Calling `GC.Collect()` doesn't help either.
Loading the data, and creating the 54326 documents does not increase memory usage significantly. Memory jumps when I add the documents using either `writer.AddDocuments(docs);` or `writer.AddDocument(doc);`
I've even tried creating a seperate method:
```cs
        private void WriteDocuments(IEnumerable<IEnumerable<IIndexableField>> docs)
        {
            using var analyzer = new KeywordAnalyzer();
            using var directory = FSDirectory.Open(IndexPath);
            var config = new IndexWriterConfig(LuceneVersion, analyzer)
            {
                OpenMode = OpenMode.CREATE, // Use OpenMode.CREATE to overwrite, or OpenMode.APPEND to just open
                RAMBufferSizeMB = 100,
                RAMPerThreadHardLimitMB = 100,
            };

            using var writer = new IndexWriter(directory, config);
            foreach (var doc in docs)
            {
                writer.AddDocument(doc);
            }
            writer.Commit();
            writer.Dispose();
            directory.Dispose();
            analyzer.Dispose();
        }
```
And calling `GC.Collect()` afterwards - no effect.

We're currently running this in a Singleton service in an Umbraco 10 project - both the Umbraco project, and the project the search is in targets `net6.0`. We are not using `.NET Standard 2.0` - but we have no global variables.

Also we're using `LuceneVersion.LUCENE_48`.

I think the next thing I want to try out is running it in a Console App, outside of Umbraco, and see how memory behaves with 54326 documents with similar search fields.

I'll write again on what I'll find.

It seems weird to me that the NuGet package is so popular (18,671,634 total downloads) - yet I couldn't find anyone else reporting on memory issues... It might be our setup - will investigate :-)

**Comment by PeterOeClausen** [comment]
Created a Console Application, installed Bogus and Lucene.
I see very different results running `writer.AddDocument(document)` versus `writer.AddDocuments(documents)`:

```cs
using Bogus;
using Lucene.Net.Analysis.Core;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Lucene.Net.Store;
using Lucene.Net.Util;
using static ConsoleAppForPrototyping.Program;

namespace ConsoleAppForPrototyping {
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            var p = new Program();
            p.Run();
            Console.WriteLine("Done creating index!");
            while (true) { }
        }

        public class Row
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public DateTime Date { get; set; }
        }

        public void Run()
        {
            var rowFaker = new Faker<Row>()
                .StrictMode(true)
                .RuleFor(o => o.Id, f => Guid.NewGuid())
                .RuleFor(o => o.Name, f => f.Name.FullName())
                .RuleFor(o => o.Date, f => f.Date.Future());

            var luceneVersion = LuceneVersion.LUCENE_48;
            using var analyzer = new KeywordAnalyzer();
            using var directory = FSDirectory.Open("../../../App_Data");
            var config = new IndexWriterConfig(luceneVersion, analyzer)
            {
                OpenMode = OpenMode.CREATE,
            };
            using var writer = new IndexWriter(directory, config);

            // Config
            for (int i = 0; i < 1000000; i++)
            {
                if(i % 100 == 0)
                {
                    Console.WriteLine(i);
                }
                var row = rowFaker.Generate();

                var document = new Document();
                document.Add(new StringField("id", row.Id.ToString(), Field.Store.YES));
                document.Add(new StringField("name", row.Name, Field.Store.YES));
                document.Add(new StringField("date", row.Date.ToString(), Field.Store.YES));
                writer.AddDocument(document);
            }

            writer.Commit();
            writer.Dispose();
            directory.Dispose();
            analyzer.Dispose();
        }
    }
}
```
![image](https://user-images.githubusercontent.com/6975621/208662017-302591ea-210e-4aa2-8e56-bdfec38ac961.png)

Stuff is added and released from memory with `writer.AddDocument(document)`, ending up consuming 56mb.

**Versus**:
```cs
using Bogus;
using Lucene.Net.Analysis.Core;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Lucene.Net.Store;
using Lucene.Net.Util;
using static ConsoleAppForPrototyping.Program;

namespace ConsoleAppForPrototyping {
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            var p = new Program();
            p.Run();
            Console.WriteLine("Done creating index!");
            while (true) { }
        }

        public class Row
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public DateTime Date { get; set; }
        }

        public void Run()
        {
            var rowFaker = new Faker<Row>()
                .StrictMode(true)
                .RuleFor(o => o.Id, f => Guid.NewGuid())
                .RuleFor(o => o.Name, f => f.Name.FullName())
                .RuleFor(o => o.Date, f => f.Date.Future());

            var luceneVersion = LuceneVersion.LUCENE_48;
            using var analyzer = new KeywordAnalyzer();
            using var directory = FSDirectory.Open("../../../App_Data");
            var config = new IndexWriterConfig(luceneVersion, analyzer)
            {
                OpenMode = OpenMode.CREATE, // Use OpenMode.CREATE to overwrite, or OpenMode.APPEND to just open
            };
            using var writer = new IndexWriter(directory, config);

            // Config
            var documentList = new List<Document>();
            for (int i = 0; i < 1000000; i++)
            {
                if(i % 100 == 0)
                {
                    Console.WriteLine(i);
                }
                var row = rowFaker.Generate();

                var document = new Document();
                document.Add(new StringField("id", row.Id.ToString(), Field.Store.YES));
                document.Add(new StringField("name", row.Name, Field.Store.YES));
                document.Add(new StringField("date", row.Date.ToString(), Field.Store.YES));
                documentList.Add(document);
            }
            writer.AddDocuments(documentList);

            writer.Commit();
            writer.Dispose();
            directory.Dispose();
            analyzer.Dispose();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/6975621/208663974-acd01214-3858-4451-bc49-bc2fcc1aa5a3.png)
First it consumes up to 6 GB.

And after 4.5 minutes it runs garbage collection and ends up at 609mb.
![image](https://user-images.githubusercontent.com/6975621/208664233-dbe00475-4172-4943-9b23-f9a9f4261d63.png)

**Two things I found:**

1) It seems to me that `writer.AddDocument(document);` handles memory better in this scenario
2) Garbage collection does pick it up, though it may take some time (in second senario 4,5 minutes).

So I think I'll experiment further with our project and use `.AddDocument(document);` instead of `.AddDocuments(documents);`.

**Comment by rclabo** [comment]
Hi @PeterOeClausen - Thanks for sharing your code for your two approaches.  This helps alot.  I'm not so sure that the memory differences you are seeing have anything to do with LuceneNET per se.  

The key reason you see so much memory allocation with `writer.AddDocuments`  is that the `documentList` you are passing has a million documents in it.  So this memory allocation is happening simply due to building the `documentList` even if you never call `writer.AddDocuments`. 

 If you were calling `writer.AddDocuments` with a list of 10 documents and called that in a loop 100,000 times then the memory allocations would be much closer to what you are seeing by calling `writer.AddDocument` with a single document done 1 million times.

One final note,  even for the `writer.AddDocument` case you can reduce allocations further if you like.  You can use the same `Document` over and over by settings it's values before calling `writer.AddDocument` . In this way there is only ever one `Document` allocated rather then 1 millions that eventually need to be garbage collected.
