### ISSUE TITLE
UpdateDocuments API should allow multiple Terms as DeleteDocuments do

### ISSUE THREAD

**Issue by Evengard** [apache/lucenenet#788]
Hello!

It seems weird, that while `IndexWriter.DeleteDocuments` accepts multiple `Term`s, `IndexWriter.UpdateDocuments` accepts only one. This makes updating multiple documents (aka with different IDs) go through the singular `IndexWriter.UpdateDocument` calls for each of them, or use `DeleteDocuments` and then `AddDocuments` manually (honestly, no idea which is better, for now I stick with multiple `UpdateDocument` calls).

Would it be possible to make the API accept multiple `Term`s so that we could update multiple documents more effectively?

**Comment by rclabo** [comment]
It's not as simple as adding support for multiple terms because you probably want to update each document with a different document.  :-)

**Comment by Evengard** [comment]
Well, actually, under the hood it is just atomic delete and add anyway. So we can just delete all matching terms and add all new documents under the hood, I guess...

I may be wrong though.

**Comment by rclabo** [comment]
I think that's true.  So I guess you'd like to pass in a list of terms and a list of documents to UpdateDocuments? Semantically that feels weird but I get the logic of it.

**Comment by Evengard** [comment]
Yeah, something like that. It may feel weird, but it kinda mimics the DeleteDocuments API too.
Maybe it would be viable to have both variants (with one Term and with a list of Terms), but I'm unsure it is beneficial.

**Comment by Evengard** [comment]
Now that I think about it, maybe it even should have a Query overload as well, like DeleteDocuments do.

**Comment by NightOwl888** [comment]
This sort of decision should probably be left up to the lucene Java team to decide how to handle. This goes beyond porting from Java to .NET and gets into the design of the application itself. You can start a discussion about this on the [lucene dev mailing list or on Slack](https://lucene.apache.org/core/discussion.html).
