### ISSUE TITLE
Wrong parsing of terms in quotes

### ISSUE THREAD

**Issue by maxiptah** [apache/lucenenet#789]
A single query like
name:"search"
is parsed as a TermQuery, whereas a search string in quotes is a phrase and therefore should be parsed as PhraseQuery (with exactly one word).

name:search would be a TermQuery, which is parsed correctly.

**Comment by rclabo** [comment]
I don't see how it would produce different results. 

Seems like a `PhraseQuery` of one world would rightly result in a `TermQuery`.  Wouldn't you think?

**Comment by NightOwl888** [comment]
There doesn't seem to be an issue to solve here. It is more or less a complaint about the design. If this is an issue for you, please take it up with the [Lucene team](https://github.com/apache/lucene/issues) and they will either be able to address this or tell you why it does what it does.
