### ISSUE TITLE
Task: Investigate slow tests in Lucene.Net.Facet

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#836]
This has been a known issue for quite a while. Some of the tests in Lucene.Net.Facet are running much slower than they do in Lucene 4.8.1.

While the tests are randomized so they vary quite a bit. These are consistently slower than they are in Java. These are some comparisons to demonstrate approximately what the gap is. These are results from Java SE 7 vs .NET 6.0.

| Test | Lucene Duration | Lucene.NET Duration   | 
|---|---|---|
| `TestDirectoryTaxonomyWriter.TestConcurrency()`  | 4.5 s  | 10.7 s  |
|  `TestAddTaxonomy.TestBig()` | 10.9 s  |  16.7 s |
|  `TestTaxonomyCombined.TestTaxonomyRefreshRaces()` | 16.1 s  |  46.2 s |

The other tests seem very reasonable in terms of performance. In the past, we have seen this sort of thing happen due to locking contention and we successfully overcame it by reviewing locks both in Lucene and in the JDK to make sure of several things:

1. That we are not missing a lock.
2. That we are correctly sharing locks between subclass and superclass.
3. That all collection types are being locked appropriately and that the implementation of the collection locks in a similar way in both environments. This is where some pretty big gaps are between Java and .NET.
4. If we still haven't found the issue, revert back to "plain old locks" (in our case `UninterruptableMonitor.Enter(syncLock)`) instead of using more advanced techniques that are available in C# to avoid locks, such as `ReaderWriterLockSlim`.

Lucene.Net.Facet has been refactored several times to try various ways to synchronize locks so it would be prudent to go back to basics to find a solution that is stable first. Once we have found a stable solution, we can begin looking at ways to avoid locks and ease into them to ensure concurrency is stable.

**Comment by Jeevananthan-23** [comment]
@NightOwl888, as a part of investigating Lucene.Net.Facet and making sure the concurrency for DrillSideways class should implement as Lucene(Java) DrillSideways implementation with ConcurrentDrillSideways [here](https://github.com/apache/lucene/blob/0a525ce2aba572855ce045e77f3a8c9acac5a199/lucene/facet/src/java/org/apache/lucene/facet/DrillSideways.java#L123) 

 On large document set, the single threaded collection can be really slow #817
