### ISSUE TITLE
AnalyzingInfixSuggesterTest.TestRandomNRT() failure

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#839]
I checked out commits one at a time and it looks like the failure goes back to #825. There appears to be more to this fix than just what we got. This is going to take some work to sort through. To get the diff of everything that changed in the test between 4.8.1 and https://github.com/apache/lucene/commit/c1fe88b7c6fa861d5101f9702a7832d29b8032ee use the command:

```console
git diff releases/lucene-solr/4.8.1..c1fe88b7c6fa861d5101f9702a7832d29b8032ee -- lucene/suggest/src/test/org/apache/lucene/search/suggest/analyzing/AnalyzingInfixSuggesterTest.java
```

For now, I will revert #825 as this is halting progress, but we should either:

1. Find a solution to this and revert the revert. Then add the other patches that are needed to get this test to pass.
2. Find an alternative solution to the virtual method call issue.

The `AnalyzingInfixSuggesterTest.TestRandomNRT()` test is being skipped in GitHub Actions because it is marked `[Slow]`, which is why we didn't catch this earlier.

**Comment by laimis** [comment]
That's a shame, I should have known it was too good to be true as a fix.

**Comment by laimis** [comment]
AnalyzingInfixSuggester has been modified to use config factory (#848) and we technically do not need #825 anymore. Still eventually we will get to the modifications in 825 but it will be as part of move to versions beyond 4.8.
