### ISSUE TITLE
EdgeNGramFilter: .NET seems to be missing PreserveOriginal

### ISSUE THREAD

**Issue by andreaCosm** [apache/lucenenet#859]
Without the option to change, what is the default behavior of terms over the maxgram?
_____
https://lucene.apache.org/core/7_5_0/analyzers-common/org/apache/lucene/analysis/ngram/EdgeNGramTokenFilter.html#EdgeNGramTokenFilter-org.apache.lucene.analysis.TokenStream-int-int-boolean-

EdgeNGramTokenFilter
public EdgeNGramTokenFilter([TokenStream](https://lucene.apache.org/core/7_5_0/core/org/apache/lucene/analysis/TokenStream.html?is-external=true) input,
                            int minGram,
                            int maxGram,
                            boolean preserveOriginal)

Creates an EdgeNGramTokenFilter that, for a given input term, produces all edge n-grams with lengths >= minGram and <= maxGram. Will optionally preserve the original term when its length is outside of the defined range.

Parameters:
input - [TokenStream](https://lucene.apache.org/core/7_5_0/core/org/apache/lucene/analysis/TokenStream.html?is-external=true) holding the input to be tokenized
minGram - the minimum length of the generated n-grams
maxGram - the maximum length of the generated n-grams
**_preserveOriginal - Whether or not to keep the original term when it is outside the min/max size range._**

**Comment by NightOwl888** [comment]
The `preserveOriginal` parameter wasn't added until a later version of Lucene than 4.8.1, which is what the `Lucene.Net.Analysis.Common` assembly is based upon. We will eventually be porting the latest version of Lucene, but until then you will need to port over "future" features if you need them. Analysis components in particular are easy to implement by end users.
