### ISSUE TITLE
I have an issue in the x86 version of application

### ISSUE THREAD

**Issue by ahmadmdabit** [apache/lucenenet#861]
Hello,
The x64 version of the application, the lucene works fine. However, There many issues using the x86 version.
1. At first, using the `AddIndexes()` method  in `MergeIndex()` method leads to **OutOfMemoryException** when the sub index to be merged with the main one, the sub is large enough.
2. I did a walkthrough around that I query a range in the sub index and index it in the main one. But after completing I should call `InitReader()` method where another exception thrown **'Not enough memory resources are available to process this command.'**.
Note: You can find that in my gist in the file: [LuceneIndexerSingleton.cs](https://gist.github.com/ahmadmdabit/a6cf1ad70da3c18c91f433a9da52230c#file-luceneindexersingleton-cs)

Regards.

**Comment by NightOwl888** [comment]
Looks like the approach that you are using to pass in the documents won't scale:

https://gist.github.com/ahmadmdabit/a6cf1ad70da3c18c91f433a9da52230c#file-luceneindexer-cs-L183

`J2N.Collections.Generic.List<T>` requires all documents to be stored in RAM at once when it is passed into this method. To make it scale, you should aim to add the documents in small batches and only load the data for the current batch. You can further reduce memory allocations by reusing the same `Document` instance and adding it over and over with different data in it each time.

Also, you have `InitReader()` and `InitWriter()`. You should only ever use one of these at a time (not sure if you are doing that, but this design allows both). If you have an open `IndexWriter` instance, you can get a reader by calling the `IndexWriter.GetReader()` method.

Anyway, this is not a bug with Lucene.NET so it doesn't belong in GitHub issues. Please refer any usability issues to StackOverflow (be sure to include both the `lucene.net` and `lucene` tags) or the [Lucene.NET user mailing list](https://lucenenet.apache.org/contributing/index.html#ask-a-question) where you are more likely to get a timely answer.
