### ISSUE TITLE
Wildcards does not work with query string containing Hyphen

### ISSUE THREAD

**Issue by gkatoch** [apache/lucenenet#869]
**Description:**
I am using StandardAnyalzer to retrieve the stored data using wildcards. This works fine for almost all cases but when I use a wildcard with a restricted character like Hyphen, the matching data is not retrieved.

**Steps to reproduce:**
You can run the following code to see this behavior:

```
public static void Test()
        {
            // Use an in-memory index.
            var indexDirectory = new RAMDirectory();
            
            Analyzer analyzer = new StandardAnalyzer(LuceneVersion.LUCENE_48);
            
            using (var writer = new IndexWriter(indexDirectory, new IndexWriterConfig(LuceneVersion.LUCENE_48, analyzer)))
            {
                var document = new Document
                {
                    new TextField("content", "This is just some text", Field.Store.YES),
                    new TextField("cataloguenumber", "DF-TESTER", Field.Store.YES)
                };
                writer.AddDocument(document);
            }
            var parser = new MultiFieldQueryParser(
                LuceneVersion.LUCENE_48,
                new[] { "cataloguenumber", "content" },
                analyzer)
            {
                AllowLeadingWildcard = true
            };

            var directoryReader = DirectoryReader.Open(indexDirectory);
            var searcher = new IndexSearcher(directoryReader);
            
            DoSearch("DF-TES", parser, searcher); // Returns the matching document
            
            DoSearch("DF-TES*", parser, searcher); // Does not return anything
        }

        private static void DoSearch(string queryString, MultiFieldQueryParser parser, IndexSearcher searcher)
        {
            var query = parser.Parse(queryString);

            var docs = searcher.Search(query, 10);

            foreach (var scoreDoc in docs.ScoreDocs)
            {
                var searchHit = searcher.Doc(scoreDoc.Doc);
                var cataloguenumber = searchHit.GetValues("cataloguenumber").FirstOrDefault();
                var content = searchHit.GetValues("content").FirstOrDefault();
                Console.WriteLine($"Found object: {cataloguenumber} {content}");
            }
        }
```
When I run the above code, method `DoSearch` with query string: `DF-TES` returns the valid result, however with `DF-TES*` this does not return anything. It looks like the query is not rewritten correctly when I am adding a Wildcard and hence leading to this behavior.

**Expected behavior**
On running the above example with wildcards we should get the matching result set.

Let me know if any more details are needed or if I haven't understood this correctly.
This works fine with WhiteSpaceAnayzer. I want to use StandardAnalyzer as this is case-insensitive and returns better AND-ed matching results when query strings have spaces.

**Comment by NightOwl888** [comment]
`StandardAnalyzer` is the wrong tool for the job. See: https://stackoverflow.com/questions/3612761/searching-hyphenated-words-with-lucene

Note that we don't use jflex or any other form of generation in .NET, so if you need to modify the `StandardAnalyzer` behavior, you will either have to do the `StandardTokenizer` code generation in Java and then port it to C# or analyze and modify the C# code directly of `StandardTokenizer.cs`. Or simply use `WhiteSpaceTokenizer` with a `LowercaseFilter` as suggested in the comments.
