### ISSUE TITLE
ci: Ensure SonarCloud is not triggered on website or documentation updates

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#873]
Our GitHub Actions for building components are not triggered for website or documentation updates, but SonarCloud currently doesn't have the filters to ignore the files that are not part of the software. To remedy this, the following exclusions should be made to the paths of the `sonar.yml` workflow:

- `'!.editorconfig'`
- `'!.gitattributes'`
- `'!.rat-excludes'`
- `'!azure-pipelines.yml'`
- `'!build'`
- `'!build.bat'`
- `'!**/*.md'`
- `'!**/*.ps1'`
- `'!**/*.psd1'`
- `'!**/*.psm1'`
- `'!**/*.txt'`
- `'!/.build/azure-templates/**/*'`
- `'!/.build/psake/**/*'`
- `'!/.vscode/**/*'`
- `'!/branding/**/*'`
- `'!/lib/**/*'`
- `'!/src/docs/**/*'`
- `'!/websites/**/*'`

**Comment by farQtech** [comment]
Hi @NightOwl888, I am interested in taking up this task. Kindly assign it to me.

**Comment by NightOwl888** [comment]
I have assigned it to you. Thanks.
