### ISSUE TITLE
Add a link and info about the Lucene.NET Slack channel

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the documentation issue

We set up a Slack channel (provided by Apache) some time ago, but it hasn't found its way yet onto our [Contributing](https://lucenenet.apache.org/contributing/index.html#getting-involved) section.

OpenNLP (another Apache project) has their Slack channel as an official way to contact them. Here is what their page looks like: https://opennlp.apache.org/get-involved.html

### Additional context

The Apache docs for Slack are here: https://infra.apache.org/slack.html.

The channel is located at: [#lucenenet-dev](https://the-asf.slack.com/archives/C03FFRQQ2RM)

**Comment by jaivardhan-bhola** [comment]
Can I work on this?

**Comment by NightOwl888** [comment]
@jaivardhan-bhola - Sure. I have assigned it to you. Let us know if you need any assistance.

**Comment by jaivardhan-bhola** [comment]
Lemme know if other changes are needed.

**Comment by NightOwl888** [comment]
These changes are now live: https://lucenenet.apache.org/contributing/index.html#slack-channel
