### ISSUE TITLE
Lucene.Net.Store.Azure.AzureDirectory: Enable usage with a sasuri and existing containers

### ISSUE THREAD

**Issue by haavardeikeland** [apache/lucenenet#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I'd like the Lucene.Net.Store.Azure.AzureDirectory to be enabled for usage with sasuri with existing containers instead of using the storage account connectionstring. Reason: to constrain access to containers for multiple usages on the same storage account.

**Comment by NightOwl888** [comment]
@Shazwazza - Thanks for the info.

It seems this is not pertinent to our project as it is not something we maintain here, so I am closing this.
