### ISSUE TITLE
ShingleFilter produces invalid queries

### ISSUE THREAD

**Issue by tohidemyname** [apache/lucenenet#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ShingleFilter uses the position length attribute of the token stream to encode the number of terms they put in a single token.
This breaks the query parsing because it creates disconnected graphs.

### Steps To Reproduce

I will implement a test case to show the bug. 

### .NET Version

8.0.300

### Operating System

win 10

**Comment by tohidemyname** [comment]
My patch is submitted: https://github.com/apache/lucenenet/pull/944

**Comment by tohidemyname** [comment]
Sorry. I am unfamiliar with submitting pull requests. I may wrongly close my pull request. I have submitted a new pull request.
https://github.com/apache/lucenenet/pull/946

**Comment by paulirwin** [comment]
Fixed in #946 (did not auto-close due to formatting)
