### ISSUE TITLE
It's not possible to extract terms from HighFreqTerms

### ISSUE THREAD

**Issue by VahidN** [apache/lucenenet#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's not possible to [GetTermText()](https://github.com/apache/lucenenet/blob/0d7bba7a42a89a3e348c6c27370425b4db33b492/src/Lucene.Net.Misc/Misc/HighFreqTerms.cs#L80C116-L80C138) from HighFreqTerms, because it's defined as an [internal](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Misc/Misc/TermStats.cs#L41) method.

### Expected Behavior

Make the [GetTermText()](https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Misc/Misc/TermStats.cs#L41) method `public`.

### Lucene.NET Version

4.8.0-beta00016

### .NET Version

.NET 8x

**Comment by paulirwin** [comment]
@VahidN Thanks for the feedback. It looks like even in the latest Java Lucene that method is still package-private (kinda-sorta how Java spells "internal") from its default visibility: https://github.com/apache/lucene/blob/b59a357e58611b86e4cc1643794e05dd17d71b08/lucene/misc/src/java/org/apache/lucene/misc/TermStats.java#L35

However, the `termtext` field is public in the upstream code (including in 4.8.0), so we incorrectly ported that as internal: https://github.com/apache/lucene/blob/b59a357e58611b86e4cc1643794e05dd17d71b08/lucene/misc/src/java/org/apache/lucene/misc/TermStats.java#L23

It seems like the most correct fix here is to make the field public (and possibly make it a property like the ones below it), and leave the visibility of `GetTermText()` as internal, although making it public too does seem like a harmless change that could be Lucene.Net-specific.

**Comment by NightOwl888** [comment]
`HighFreqTerms` is not intended to be copied into another app to use. In Java, you can simply call it on the command line by providing the name of the class to find an entry point on. However, in .NET we cannot do that. A DLL can either be defined as a class library or have an entry point, not both.

So, we provide a wrapper CLI tool, [lucene-cli](https://lucenenet.apache.org/docs/4.8.0-beta00016/cli/index.html) to execute the commands that Lucene provides as command line tools (except for a few that didn't appear to be useful). The [list-high-freq-terms command](https://lucenenet.apache.org/docs/4.8.0-beta00016/cli/index/list-high-freq-terms.html) can be used directly by end users, so there is generally no need to copy and paste the `HighFreqTerms` file into a console project to run.

Of course, as @paulirwin pointed out, the `termtext` field should be made into a public property to match Lucene, so I am marking this issue as a bug so we can track it.

**Comment by NightOwl888** [comment]
It seems like it would also be a good idea to search the codebase for `Main(` and add a comment on each of those methods as well as the header of the class (if present and is only to be used as a CLI tool) that these commands are available through `lucene-cli` with a link to the [NuGet package](https://www.nuget.org/packages/lucene-cli) so we don't keep getting reports like this one.
