### ISSUE TITLE
Missing groups from GroupingSearch

### ISSUE THREAD

**Issue by dongle-the-gadget** [apache/lucenenet#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

GroupingSearch might miss some groups, even if searching for docs using `IndexSearcher.Search` indicates that the group should be present.

For instance, using `IndexSearcher.Search` will reveal a document with field `name` and value `CreateFileW`, but using `GroupingSearch`, like below:
```cs
GroupingSearch groupingSearch = new("name");
groupingSearch.SetAllGroups(true);

// query here works with IndexSearcher.Search
var groups = groupingSearch.Search(searcher, query, 0, 10);

// groups variable doesn't contain all the possible groups.
```
contains no group with the `name` being `CreateFileW`.

In addition, the `TotalGroupCount` is inconsistent with that of the real dataset (in the repro below `GroupingSearch` returns 4 instead of the expected 10).

### Expected Behavior

The group should exist in the search, and there should not be a mismatch between `TotalGroupCount` and the index.

### Steps To Reproduce

A repro repository is here: https://github.com/dongle-the-gadget/TestLucene

The real dataset has documents of the following `name`s:
```
CreateFile2
CreateFile2FromAppW
CreateFileA
CreateFileFromAppW
CreateFileMappingA
CreateFileMappingFromApp
CreateFileMappingW
CreateFileMoniker
CreateFileW
CreateFile2
```

### Lucene.NET Version

4.8.0-beta00016

### .NET Version

8.0

### Operating System

Windows 11

**Comment by paulirwin** [comment]
I'll take investigating this one for the beta 18 release.

**Comment by paulirwin** [comment]
Hi @dongle-the-gadget, thanks for the detailed report and code sample. I was able to reproduce your findings. However, I regret to say that this is correct behavior, so the problem likely lies in how you're creating your index.

I was able to reproduce the exact same behavior in Java Lucene 4.8.1, so this is not a bug in Lucene.NET. Java code below if you're curious.

The problem seems to be due to whatever Analyzer you're using breaking the name values into smaller "terms." I opened the index with [Luke 4.8.0](https://github.com/DmitryKey/luke) and it shows the following terms for the name field: a, app, create, file, file2, from, mapping, moniker, and w. When using the GroupingSearch that takes a string in the constructor, that does a Term-based grouping, so it can only group by those terms. If you inspect the group value of each group, you'll see that the matches (the 4 you were seeing) were: file, mapping, w, and moniker.

If you want to group by the full field value, you will either need to index with an analyzer that does not break the value into those smaller terms, or potentially use a different grouping strategy.

```java
package org.example;

import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.PhraseQuery;
import org.apache.lucene.search.grouping.GroupingSearch;
import org.apache.lucene.search.grouping.TopGroups;
import org.apache.lucene.store.FSDirectory;
import org.apache.lucene.util.BytesRef;

import java.io.File;

public class Main {
    public static void main(String[] args) throws Exception {
        FSDirectory directory = FSDirectory.open(new File("LuceneIndex"));
        DirectoryReader reader = DirectoryReader.open(directory);
        IndexSearcher searcher = new IndexSearcher(reader);

        PhraseQuery query = new PhraseQuery();
        query.add(new org.apache.lucene.index.Term("name", "create"));
        query.add(new org.apache.lucene.index.Term("name", "file"));

        var docs = searcher.search(query, 53);
        boolean hasRequiredDoc = false;
        for (var doc : docs.scoreDocs)
        {
            var document = searcher.doc(doc.doc);
            if (document.get("name").equals("CreateFileW"))
            {
                hasRequiredDoc = true;
                break;
            }
        }

        GroupingSearch groupingSearch = new GroupingSearch("name");
        groupingSearch.setAllGroups(true);

        TopGroups<BytesRef> groups = groupingSearch.search(searcher, query, 0, 10);
        boolean hasRequiredGroup = false;

        for (var group : groups.groups)
        {
            System.out.println("Group: " + group.groupValue.utf8ToString());

            var firstDoc = group.scoreDocs[0];
            var doc = searcher.doc(firstDoc.doc);

            if (doc.get("name").equals("CreateFileW"))
            {
                hasRequiredGroup = true;
                break;
            }
        }

        System.out.println(hasRequiredDoc);
        System.out.println(hasRequiredGroup);
    }
}
```

**Comment by NightOwl888** [comment]
Note that [`KeywordAnalyzer`](https://github.com/apache/lucenenet/blob/7cfc4c340c384bd5af39f42d7591dbe45344fd24/src/Lucene.Net.Analysis.Common/Analysis/Core/KeywordAnalyzer.cs)/[`KeywordTokenizer`](https://github.com/apache/lucenenet/blob/7cfc4c340c384bd5af39f42d7591dbe45344fd24/src/Lucene.Net.Analysis.Common/Analysis/Core/KeywordTokenizer.cs) are suitable for the purpose of not splitting apart values like this.

You can use `PerFieldAnalyzerWrapper` in a custom analyzer to specify that the `name` field will use `KeywordAnalyzer` while all other fields will use `StandardAnalyzer`.

```c#
using Lucene.Net.Analysis;
using Lucene.Net.Analysis.Core;
using Lucene.Net.Analysis.Standard;

public class CustomAnalyzer : Analyzer
{
    private readonly Analyzer _defaultAnalyzer;
    private readonly PerFieldAnalyzerWrapper _perFieldAnalyzerWrapper;

    public CustomAnalyzer()
    {
        // Default analyzer for most fields
        _defaultAnalyzer = new StandardAnalyzer(Lucene.Net.Util.LuceneVersion.LUCENE_48);

        // Define the per-field analyzers
        var perFieldAnalyzers = new Dictionary<string, Analyzer>
        {
            { "name", new KeywordAnalyzer() } // Use KeywordAnalyzer for "name"
        };

        // Combine default and per-field analyzers
        _perFieldAnalyzerWrapper = new PerFieldAnalyzerWrapper(_defaultAnalyzer, perFieldAnalyzers);
    }

    protected override TokenStreamComponents CreateComponents(string fieldName, System.IO.TextReader reader)
    {
        // Delegate to the PerFieldAnalyzerWrapper
        return _perFieldAnalyzerWrapper.GetWrappedAnalyzer(fieldName).CreateComponents(fieldName, reader);
    }

    protected override TextReader InitReader(string fieldName, TextReader reader)
    {
        return _perFieldAnalyzerWrapper.InitReader(fieldName, reader);
    }
}

```
