### ISSUE TITLE
Create a separate nuget packages for some interesting functions.

### ISSUE THREAD

**Issue by alkampfergit** [apache/lucenenet#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

The folder src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous contains lots of interesting classes, like ASCIIFoldingFilter. I was not able to find a viable alternative with that level of details around there, but to use it I need to reference the entire Lucene.NET library.

It could be interesting having these classes published as a general utilities without the need to reference the entire library.

**Comment by NightOwl888** [comment]
As this is a faithful port of Java Lucene 4.8.0, it is not very sensible for us to break up the code into more pieces unless there is a good reason to. That said, if you have a complaint about the way the project is organized, it would be best to address it to [Lucene](https://github.com/apache/lucene) so it can be addressed upstream before being ported here.
